Repository kubernetes-sigs/cluster-api-provider-ibmcloud, pull requests merged in 2019-08, with the labels that each got.

#273 Change label to area/provider/ibmcloud
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: approved, area/provider/ibmcloud, cncf-cla: yes, lgtm, size/XS

#274 Changes related to sig ibm cloud rename
  OWNERS
  OWNERS_ALIASES
  README.md
Labels: approved, area/provider/ibmcloud, cncf-cla: yes, lgtm, size/S

#275 UBUNTU_LATEST does not work
  Makefile
  cmd/clusterctl/examples/ibmcloud/provider-component/user-data/ubuntu/templates/master-user-data.sh
  cmd/clusterctl/examples/ibmcloud/provider-component/user-data/ubuntu/templates/worker-user-data.sh
Labels: approved, cncf-cla: yes, lgtm, size/S
