Repository kubernetes-sigs/cluster-api-provider-ibmcloud, pull requests merged in 2019-11, with the labels that each got.

#280 Normalize variable and function naming
  pkg/apis/ibmcloud/v1alpha1/ibmcloudmachineproviderspec_types.go
  pkg/cloud/ibmcloud/clients/machines.go
  pkg/cloud/ibmcloud/deployer.go
  pkg/cloud/ibmcloud/deployer_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#281 Enabled multi-arch image build.
  .travis.yml
Labels: approved, area/provider/ibmcloud, cncf-cla: yes, lgtm, size/XS

#285 unique leader election id
  cmd/manager/main.go
Labels: approved, area/provider/ibmcloud, cncf-cla: yes, lgtm, ok-to-test, size/XS
