Repository kubernetes-sigs/cluster-api-provider-ibmcloud, pull requests merged in 2019-05, with the labels that each got.

#101 Removed sig-ibmcloud-admins.
  OWNERS
  OWNERS_ALIASES
Labels: approved, cncf-cla: yes, lgtm, size/XS

#104 Added sig ibmcloud to issues and pr template.
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#106 add generate yaml file test
  Makefile
  cmd/clusterctl/examples/ibmcloud/generate-yaml.sh
Labels: approved, cncf-cla: yes, lgtm, sig/ibmcloud, size/M

#109 Fix a typo
  cmd/clusterctl/examples/ibmcloud/generate-yaml.sh
Labels: approved, cncf-cla: yes, lgtm, sig/ibmcloud, size/XS

#108 Added Go Report Card.
  README.md
Labels: approved, cncf-cla: yes, lgtm, sig/ibmcloud, size/S

#111 update makefile to add test, build and images targets.
  .travis.yml
  Makefile
Labels: approved, cncf-cla: yes, lgtm, sig/ibmcloud, size/L

#114 Updated registry to quay.io/cluster-api-provider-ibmcloud.
  Makefile
  config/manager/manager.yaml
Labels: approved, cncf-cla: yes, lgtm, sig/ibmcloud, size/XS

#117 Added hchenxa as reviewer.
  OWNERS_ALIASES
Labels: approved, cncf-cla: yes, lgtm, sig/ibmcloud, size/XS

#118 use simple image name
  Makefile
  config/default/manager_image_patch.yaml
  config/manager/manager.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#110 Timeout flag configuration enhancement
  pkg/cloud/ibmcloud/clients/machines.go
Labels: approved, cncf-cla: yes, lgtm, sig/ibmcloud, size/S

#119 make independent binary image build
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/S

#122 Updated PR template by adding default reviewers.
  .github/PULL_REQUEST_TEMPLATE.md
Labels: approved, cncf-cla: yes, lgtm, sig/ibmcloud, size/XS

#121 add provider id
  pkg/cloud/ibmcloud/actuators/machine/actuator.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#124 fix kubebuilder issue.
  Makefile
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, sig/ibmcloud, size/S

#127 empty log message fix
  Gopkg.lock
  Gopkg.toml
  vendor/k8s.io/klog/klog.go
  vendor/k8s.io/klog/klog_file.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#128 Phase
  config/rbac/rbac_role.yaml
  pkg/cloud/ibmcloud/actuators/machine/actuator.go
Labels: approved, cncf-cla: yes, lgtm, sig/ibmcloud, size/M

#130 Add rtheis
  OWNERS_ALIASES
Labels: approved, cncf-cla: yes, lgtm, size/XS

#129 Added ubuntu machine sample file.
  examples/ubuntu/machines.yaml
Labels: approved, cncf-cla: yes, lgtm, sig/ibmcloud, size/M

#133 fix build-push-images target.
  Makefile
Labels: approved, cncf-cla: yes, lgtm, sig/ibmcloud, size/XS

#134 update contributing doc.
  CONTRIBUTING.md
Labels: approved, cncf-cla: yes, lgtm, sig/ibmcloud, size/M

#136 typo correct: IBM Cloud is the right name
  README.md
Labels: approved, cncf-cla: yes, lgtm, sig/ibmcloud, size/XS

#137 Update README.md
  README.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, sig/ibmcloud, size/XS

#138 the latest tag doesn't exist
  config/default/manager_image_patch.yaml
  config/manager/manager.yaml
Labels: approved, cncf-cla: yes, lgtm, sig/ibmcloud, size/XS

#142 Add machine deleting status
  pkg/cloud/ibmcloud/actuators/machine/actuator.go
Labels: approved, cncf-cla: yes, lgtm, sig/ibmcloud, size/XS

#141 change name of manager statefulset
  config/manager/manager.yaml
Labels: approved, cncf-cla: yes, lgtm, sig/ibmcloud, size/XS

#145 Add doc about private key location
  README.md
Labels: approved, cncf-cla: yes, lgtm, sig/ibmcloud, size/XS

#147 Restore manifests build stage
  Makefile
Labels: approved, cncf-cla: yes, lgtm, sig/ibmcloud, size/XS

#149 check guest if empty before use it.
  pkg/cloud/ibmcloud/actuators/machine/actuator.go
Labels: approved, cncf-cla: yes, lgtm, sig/ibmcloud, size/XS

#107 add event handling for create and delete
  cmd/manager/main.go
  pkg/cloud/ibmcloud/actuators/machine/actuator.go
  pkg/record/record.go
Labels: approved, cncf-cla: yes, lgtm, sig/ibmcloud, size/M

#152 os reference code document
  README.md
  docs/ibmcloud_help.md
Labels: approved, cncf-cla: yes, lgtm, sig/ibmcloud, size/S

#156 Add Datacenter into help info doc
  docs/ibmcloud_help.md
Labels: approved, cncf-cla: yes, lgtm, sig/ibmcloud, size/XS

#150 update: when a machine specification changes, recreate the machine
  pkg/cloud/ibmcloud/actuators/machine/actuator.go
  pkg/cloud/ibmcloud/clients/machines.go
Labels: approved, cncf-cla: yes, lgtm, sig/ibmcloud, size/L

#151 get vm by name instead of search in a list
  Gopkg.lock
  pkg/cloud/ibmcloud/actuators/machine/actuator.go
  pkg/cloud/ibmcloud/clients/machines.go
  vendor/github.com/softlayer/softlayer-go/filter/filters.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#157 support latest kustomize
  Makefile
  cmd/clusterctl/examples/ibmcloud/generate-yaml.sh
  cmd/clusterctl/examples/ibmcloud/provider-component/clouds-secrets/kustomization.yaml
  cmd/clusterctl/examples/ibmcloud/provider-component/cluster-api/kustomization.yaml
  cmd/clusterctl/examples/ibmcloud/provider-component/user-data/ubuntu/kustomization.yaml
Labels: approved, cncf-cla: yes, lgtm, sig/ibmcloud, size/M

#160 use kubectl for kustomize
  Makefile
  README.md
  cmd/clusterctl/examples/ibmcloud/generate-yaml.sh
Labels: approved, cncf-cla: yes, lgtm, sig/ibmcloud, size/S

#169 lower log level for VM instance provision message
  pkg/cloud/ibmcloud/clients/machines.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#168 fix phase issue
  pkg/cloud/ibmcloud/actuators/machine/actuator.go
Labels: approved, cncf-cla: yes, lgtm, sig/ibmcloud, size/XS

#171 Fix documents
  config/manager/manager.yaml
  docs/trouble_shooting.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#173 clean useless resources
  config/default/kustomization.yaml
  config/default/manager_auth_proxy_patch.yaml
  config/default/manager_image_patch.yaml
  config/default/manager_prometheus_metrics_patch.yaml
  config/kustomization.yaml
  config/manager/manager.yaml
  config/rbac/auth_proxy_role.yaml
  config/rbac/auth_proxy_role_binding.yaml
  config/rbac/auth_proxy_service.yaml
  config/rbac/rbac_role.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#177 nit:Add doctc for some files
  CONTRIBUTING.md
  RELEASE.md
Labels: approved, cncf-cla: yes, lgtm, sig/ibmcloud, size/S

#175 make .gitignore easy to maintain
  .gitignore
  cmd/clusterctl/.gitignore
  cmd/clusterctl/examples/ibmcloud/.gitignore
Labels: approved, cncf-cla: yes, lgtm, size/L

#178 update download binaries to clean dependency for kustomize
  scripts/download-binaries.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#174 Add guideline to add a new worker node
  README.md
  docs/add_node.md
Labels: approved, cncf-cla: yes, lgtm, sig/ibmcloud, size/M

#170 Add addons information
  README.md
Labels: approved, cncf-cla: yes, lgtm, sig/ibmcloud, size/S

#179 remove uselsess id annotation, we have it in PROVIDERID
  pkg/cloud/ibmcloud/actuators/machine/actuator.go
  pkg/cloud/ibmcloud/deployer.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#180 Update machine cpu to 4
  cmd/clusterctl/examples/ibmcloud/machines.yaml.template
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#182 get sshkey by filter instead of go though list
  pkg/cloud/ibmcloud/clients/machines.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#183 disable swap permanently
  cmd/clusterctl/examples/ibmcloud/provider-component/user-data/ubuntu/templates/master-user-data.sh
  cmd/clusterctl/examples/ibmcloud/provider-component/user-data/ubuntu/templates/worker-user-data.sh
Labels: approved, cncf-cla: yes, lgtm, sig/ibmcloud, size/XS

#188 the generate.sh exited when the cluster.yaml exists
  cmd/clusterctl/examples/ibmcloud/generate-yaml.sh
Labels: approved, cncf-cla: yes, lgtm, sig/ibmcloud, size/XS

#190 Enhance doc of trouble-shooting for cannot create cluster by kind
  docs/trouble_shooting.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, sig/ibmcloud, size/M

#189 format clouds.yaml for extension
  README.md
  cmd/clusterctl/examples/ibmcloud/clouds.yaml.template
  pkg/cloud/ibmcloud/clients/machines.go
  pkg/cloud/types.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#194 Add explaination for sshUserName
  README.md
  cmd/clusterctl/examples/ibmcloud/machines.yaml.template
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#195 convert Ibmcloud to IBMCloud for better UX
  cmd/clusterctl/examples/ibmcloud/cluster.yaml.template
  cmd/clusterctl/examples/ibmcloud/machines.yaml.template
  config/crds/ibmcloud_v1alpha1_ibmcloudclusterproviderspec.yaml
  config/crds/ibmcloud_v1alpha1_ibmcloudclusterproviderstatus.yaml
  config/crds/ibmcloud_v1alpha1_ibmcloudmachineproviderspec.yaml
  config/crds/ibmcloud_v1alpha1_ibmcloudmachineproviderstatus.yaml
  config/samples/ibmcloud_v1alpha1_ibmcloudclusterproviderspec.yaml
  config/samples/ibmcloud_v1alpha1_ibmcloudclusterproviderstatus.yaml
  config/samples/ibmcloud_v1alpha1_ibmcloudmachineproviderspec.yaml
  config/samples/ibmcloud_v1alpha1_ibmcloudmachineproviderstatus.yaml
  docs/add_node.md
  examples/ubuntu/machines.yaml
  pkg/apis/ibmcloud/v1alpha1/ibmcloudclusterproviderspec_types.go
  pkg/apis/ibmcloud/v1alpha1/ibmcloudclusterproviderspec_types_test.go
  pkg/apis/ibmcloud/v1alpha1/ibmcloudclusterproviderstatus_types.go
  pkg/apis/ibmcloud/v1alpha1/ibmcloudclusterproviderstatus_types_test.go
  pkg/apis/ibmcloud/v1alpha1/ibmcloudmachineproviderspec_types.go
  pkg/apis/ibmcloud/v1alpha1/ibmcloudmachineproviderspec_types_test.go
  pkg/apis/ibmcloud/v1alpha1/ibmcloudmachineproviderstatus_types.go
  pkg/apis/ibmcloud/v1alpha1/ibmcloudmachineproviderstatus_types_test.go
  pkg/apis/ibmcloud/v1alpha1/register.go
  pkg/apis/ibmcloud/v1alpha1/zz_generated.deepcopy.go
  pkg/cloud/ibmcloud/actuators/machine/machine_script.go
  pkg/cloud/ibmcloud/clients/machines.go
  pkg/cloud/types.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, sig/ibmcloud, size/L

#204 Update base image to fix security issue
  cmd/manager/Dockerfile
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, sig/ibmcloud, size/XS

#191 fix pod and node ip override issue.
  cmd/clusterctl/examples/ibmcloud/cluster.yaml.template
  docs/trouble_shooting.md
  pkg/cloud/ibmcloud/clients/machines.go
Labels: approved, cncf-cla: yes, lgtm, sig/ibmcloud, size/S

#201 Add cluster actuator support
  Gopkg.lock
  pkg/apis/ibmcloud/v1alpha1/register.go
  pkg/cloud/ibmcloud/actuators/cluster/actuator.go
  pkg/cloud/ibmcloud/actuators/machine/actuator.go
  pkg/controller/add_cluster_controller.go
Labels: approved, cncf-cla: yes, lgtm, sig/ibmcloud, size/L

#203 Add travis for building
  .travis.yml
  Makefile
  config/manager/manager.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#211 Fix VA issues for clusterctl
  cmd/clusterctl/Dockerfile
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS
