Repository kubernetes-sigs/cluster-api-provider-ibmcloud, pull requests merged in 2021-12, with the labels that each got.

#441 add support for image and network name
  api/v1alpha4/ibmpowervscluster_types.go
  api/v1alpha4/ibmpowervsmachine_types.go
  api/v1alpha4/zz_generated.deepcopy.go
  cloud/scope/powervs_clients.go
  cloud/scope/powervs_machine.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_ibmpowervsclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_ibmpowervsmachines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_ibmpowervsmachinetemplates.yaml
  docs/book/src/topics/powervs/creating-a-cluster.md
  pkg/authenticator.go
  templates/README.md
  templates/cluster-template-powervs.yaml
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, ok-to-test, size/L, approved

#442 Add netlify.toml file
  netlify.toml
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, size/S, approved

#450 Improve documentation
  docs/book/src/developer/index.md
  docs/book/src/getting-started.md
  docs/book/src/images/ibm-cloud.svg
  docs/book/src/introduction.md
  docs/book/src/topics/index.md
  docs/book/src/topics/powervs/creating-a-cluster.md
  docs/book/src/topics/powervs/index.md
  docs/book/src/topics/vpc/creating-a-cluster.md
  docs/book/src/topics/vpc/index.md
  docs/book/src/topics/vpc/prerequisites.md
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, ok-to-test, size/L, approved

#454 Watch Namespace
  main.go
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, size/S, approved

#465 Updating power-go-client to 1.0.80
  cloud/scope/powervs_clients.go
  cloud/scope/powervs_machine.go
  controllers/ibmpowervsmachine_controller.go
  go.mod
  go.sum
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, size/S, ok-to-test, approved

#466 Use proper api version
  cloud/scope/cluster.go
  cloud/scope/machine.go
  controllers/ibmvpccluster_controller.go
  controllers/ibmvpcmachine_controller.go
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, approved, size/M

#471 rename APIEndpoint to VPCEndpoint
  api/v1alpha3/ibmvpccluster_types.go
  api/v1alpha3/types.go
  api/v1alpha3/zz_generated.deepcopy.go
  api/v1alpha4/ibmvpccluster_types.go
  api/v1alpha4/types.go
  api/v1alpha4/zz_generated.deepcopy.go
  cloud/scope/cluster.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_ibmvpcclusters.yaml
  controllers/ibmvpccluster_controller.go
  controllers/ibmvpcmachine_controller.go
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, ok-to-test, size/L, approved

#472 Add doc for deployment using tilt
  docs/book/src/developer/tilt.md
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, ok-to-test, approved, size/M

#473 Add conversion doc
  docs/book/src/SUMMARY.md
  docs/book/src/developer/conversion.md
  docs/book/src/developer/index.md
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, size/S, ok-to-test, approved

#481 Use klogr for logging
  go.mod
  go.sum
  main.go
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, approved, size/M

#486 Include Compatibility matrix and update the readme
  README.md
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, size/L, approved

#487 Updating power-go-client to 1.0.85
  cloud/scope/powervs_clients.go
  cloud/scope/powervs_machine.go
  go.mod
  go.sum
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, size/S, ok-to-test, approved

#488 Add webhook for IBMPowerVS resources
  Makefile
  PROJECT
  api/v1beta1/common.go
  api/v1beta1/ibmpowervscluster_types.go
  api/v1beta1/ibmpowervscluster_webhook.go
  api/v1beta1/ibmpowervsmachine_types.go
  api/v1beta1/ibmpowervsmachine_webhook.go
  api/v1beta1/ibmpowervsmachinetemplate_types.go
  api/v1beta1/ibmpowervsmachinetemplate_webhook.go
  api/v1beta1/ibmvpccluster_types.go
  api/v1beta1/ibmvpcmachine_types.go
  api/v1beta1/zz_generated.deepcopy.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_ibmpowervsmachines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_ibmpowervsmachinetemplates.yaml
  config/crd/kustomization.yaml
  config/crd/kustomizeconfig.yaml
  config/crd/patches/cainjection_in_ibmpowervsclusters.yaml
  config/crd/patches/cainjection_in_ibmpowervsmachines.yaml
  config/crd/patches/cainjection_in_ibmpowervsmachinetemplates.yaml
  config/crd/patches/cainjection_in_ibmvpcclusters.yaml
  config/crd/patches/cainjection_in_ibmvpcmachines.yaml
  config/crd/patches/cainjection_in_ibmvpcmachinetemplates.yaml
  config/crd/patches/webhook_in_ibmpowervsclusters.yaml
  config/crd/patches/webhook_in_ibmpowervsmachines.yaml
  config/crd/patches/webhook_in_ibmpowervsmachinetemplates.yaml
  config/crd/patches/webhook_in_ibmvpcclusters.yaml
  config/crd/patches/webhook_in_ibmvpcmachines.yaml
  config/crd/patches/webhook_in_ibmvpcmachinetemplates.yaml
  config/default/kustomization.yaml
  config/default/webhookcainjection_patch.yaml
  config/webhook/manifests.yaml
  main.go
  templates/cluster-template-powervs.yaml
Labels: lgtm, area/provider/ibmcloud, size/XL, cncf-cla: yes, ok-to-test, approved

#492 support for healthz
  config/manager/manager.yaml
  main.go
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, approved, size/M

#490 Add e2e test framework
  .gitignore
  Makefile
  config/default/kustomization.yaml
  config/default/manager_pull_policy.yaml
  go.mod
  go.sum
  hack/tools/Makefile
  test/e2e/config/ibmcloud-e2e.yaml
  test/e2e/data/cni/calico/calico.yaml
  test/e2e/data/shared/metadata.yaml
  test/e2e/suite_test.go
Labels: lgtm, area/provider/ibmcloud, size/XXL, cncf-cla: yes, ok-to-test, approved

#495 Update - k8s and golang
  Dockerfile
  api/v1alpha3/zz_generated.deepcopy.go
  api/v1alpha4/zz_generated.conversion.go
  api/v1alpha4/zz_generated.deepcopy.go
  api/v1beta1/zz_generated.deepcopy.go
  cloud/scope/cluster.go
  cloud/scope/machine.go
  cloud/scope/powervs_cluster.go
  cloud/scope/powervs_machine.go
  go.mod
  go.sum
  hack/boilerplate/README.md
  hack/boilerplate/boilerplate.Dockerfile.txt
  hack/boilerplate/boilerplate.bzl.txt
  hack/boilerplate/boilerplate.generatego.txt
  hack/boilerplate/boilerplate.py
  hack/boilerplate/boilerplate.py.txt
  hack/boilerplate/boilerplate.sh.txt
  hack/tools/go.mod
  hack/tools/go.sum
Labels: lgtm, area/provider/ibmcloud, size/XL, cncf-cla: yes, approved

#498 Add v1alpha3 conversion and webhook for IBMVPC resources
  Makefile
  api/v1alpha3/conversion.go
  api/v1alpha3/doc.go
  api/v1alpha3/groupversion_info.go
  api/v1alpha3/zz_generated.conversion.go
  api/v1alpha3/zz_generated.deepcopy.go
  api/v1beta1/common.go
  api/v1beta1/ibmvpccluster_webhook.go
  api/v1beta1/ibmvpcmachine_types.go
  api/v1beta1/ibmvpcmachine_webhook.go
  api/v1beta1/ibmvpcmachinetemplate_webhook.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_ibmvpcmachines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_ibmvpcmachinetemplates.yaml
  config/crd/kustomization.yaml
  config/webhook/manifests.yaml
  main.go
Labels: lgtm, area/provider/ibmcloud, size/XXL, cncf-cla: yes, ok-to-test, approved
