Repository kubernetes-sigs/cluster-api-provider-ibmcloud, pull requests merged in 2021-03, with the labels that each got.

#310 enable metrics scraping via prometheus
  config/rbac/auth_proxy_service.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#309 fix: issue#306: support provision specified kube version cluster
  config/crd/kustomization.yaml
  templates/cluster-template.yaml
Labels: approved, area/provider/ibmcloud, cncf-cla: yes, lgtm, ok-to-test, size/XS

#311 Update klog dependency to v2
  cloud/scope/cluster.go
  cloud/scope/machine.go
  go.mod
  go.sum
Labels: approved, area/provider/ibmcloud, cncf-cla: yes, lgtm, ok-to-test, size/L

#313 #312: Fix deploy issue
  config/rbac/auth_proxy_service.yaml
  config/rbac/role.yaml
Labels: approved, area/provider/ibmcloud, cncf-cla: yes, lgtm, ok-to-test, size/M
