Repository kubernetes-sigs/cluster-api-provider-ibmcloud, pull requests merged in 2021-05, with the labels that each got.

#314 An initial design for multiple IaaS implementations in IBM Cloud
  docs/images/cluster-api-ibmcloud-definition.png
  docs/images/cluster-api-ibmcloud-powervs.png
  docs/images/cluster-api-ibmcloud-vpc.png
  docs/proposal/architecture_for_diff_iaas.md
Labels: approved, area/provider/ibmcloud, cncf-cla: yes, lgtm, ok-to-test, size/M

#318 README - add IBM Cloud VPC2 instructions
  README.md
Labels: approved, area/provider/ibmcloud, cncf-cla: yes, lgtm, ok-to-test, size/L

#322 Adding a note about qcow2 extension
  README.md
Labels: approved, area/provider/ibmcloud, cncf-cla: yes, lgtm, ok-to-test, size/XS
