Repository kubernetes-sigs/cluster-api-provider-ibmcloud, pull requests merged in 2021-09, with the labels that each got.

#335 Build multi-arch manifest image
  Dockerfile
  Makefile
  versions.mk
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, size/L, approved

#336 Add cloudbuild.yaml file
  cloudbuild.yaml
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, size/S, approved

#337 Add goreport
  README.md
Labels: lgtm, area/provider/ibmcloud, size/XS, cncf-cla: yes, approved

#339 Adding unit tests- powervs
  controllers/ibmpowervscluster_controller_test.go
  controllers/ibmpowervsmachine_controller_test.go
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, ok-to-test, size/L, approved

#340 Support JUnit XML test report
  .gitignore
  controllers/suite_test.go
  scripts/ci-test.sh
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, ok-to-test, approved, size/M
