Repository kubernetes-sigs/cluster-api-provider-ibmcloud, pull requests merged in 2022-07, with the labels that each got.

#726 Improve UT coverage for IBMPowerVS controllers
  cloud/scope/powervs_cluster.go
  cloud/scope/powervs_machine.go
  cloud/scope/powervs_test.go
  controllers/ibmpowervscluster_controller_test.go
  controllers/ibmpowervsmachine_controller_test.go
Labels: lgtm, area/provider/ibmcloud, size/XL, cncf-cla: yes, approved

#734 Improve UT coverage in cloud/scope package for VPC
  cloud/scope/cluster.go
  cloud/scope/cluster_test.go
  cloud/scope/common_test.go
  cloud/scope/machine.go
  cloud/scope/machine_test.go
  cloud/scope/powervs_test.go
  cloud/scope/suite_test.go
  controllers/ibmvpccluster_controller.go
  controllers/ibmvpcmachine_controller.go
Labels: lgtm, area/provider/ibmcloud, size/XXL, cncf-cla: yes, approved

#741 Improve UT coverage in cloud/scope package for PowerVS
  cloud/scope/cluster_test.go
  cloud/scope/common_test.go
  cloud/scope/machine_test.go
  cloud/scope/powervs_cluster_test.go
  cloud/scope/powervs_image.go
  cloud/scope/powervs_image_test.go
  cloud/scope/powervs_machine.go
  cloud/scope/powervs_machine_test.go
  cloud/scope/suite_test.go
Labels: lgtm, area/provider/ibmcloud, size/XL, cncf-cla: yes, approved

#745 Add verify-manifests target and fix config files
  Makefile
  config/crd/bases/infrastructure.cluster.x-k8s.io_ibmpowervsclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_ibmpowervsimages.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_ibmpowervsmachines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_ibmpowervsmachinetemplates.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_ibmvpcclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_ibmvpcmachines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_ibmvpcmachinetemplates.yaml
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, approved, size/M

#748 Fetch internal IP from dhcp server
  cloud/scope/powervs_machine.go
  cloud/scope/powervs_machine_test.go
  controllers/ibmpowervsmachine_controller.go
  controllers/ibmpowervsmachine_controller_test.go
  pkg/cloud/services/powervs/caching.go
  pkg/cloud/services/powervs/mock/powervs_generated.go
  pkg/cloud/services/powervs/powervs.go
  pkg/cloud/services/powervs/service.go
Labels: lgtm, area/provider/ibmcloud, size/XL, cncf-cla: yes, approved

#743 Improve UT coverage for controllers pkg
  cloud/scope/powervs_image.go
  cloud/scope/powervs_image_test.go
  controllers/ibmpowervscluster_controller_test.go
  controllers/ibmpowervsimage_controller_test.go
  controllers/ibmvpccluster_controller_test.go
  controllers/ibmvpcmachine_controller_test.go
Labels: lgtm, area/provider/ibmcloud, size/XXL, cncf-cla: yes, approved

#750 Fetch internal IP from dhcp server
  cloud/scope/powervs_machine.go
  controllers/ibmpowervsmachine_controller.go
  pkg/cloud/services/powervs/caching.go
  pkg/cloud/services/powervs/mock/powervs_generated.go
  pkg/cloud/services/powervs/powervs.go
  pkg/cloud/services/powervs/service.go
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, size/L, approved

#753 Minor UT coverage improvements
  cloud/scope/common_test.go
  cloud/scope/machine_test.go
  cloud/scope/powervs_cluster.go
  cloud/scope/powervs_image.go
  cloud/scope/powervs_machine.go
  cloud/scope/powervs_machine_test.go
  pkg/cloud/services/powervs/service.go
  pkg/endpoints/endpoints_test.go
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, size/L, approved

#760 Update cluster creation flow in doc
  docs/book/src/topics/powervs/creating-a-cluster.md
  docs/book/src/topics/vpc/creating-a-cluster.md
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, approved, size/M

#759 Remove powervs-utils package dependency
  cloud/scope/powervs_cluster.go
  cloud/scope/powervs_image.go
  cloud/scope/powervs_machine.go
  go.mod
  go.sum
  pkg/endpoints/endpoints.go
  pkg/endpoints/endpoints_test.go
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, size/L, approved

#766 Update cluster-api to v1.2.0
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
  test/e2e/config/ibmcloud-e2e-powervs.yaml
  test/e2e/config/ibmcloud-e2e-vpc.yaml
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, approved, size/M

#768 Minor IBMPowerVSImage bugfix
  cloud/scope/powervs_image.go
Labels: lgtm, area/provider/ibmcloud, size/XS, cncf-cla: yes, approved

#767 Update golang to 1.18.4
  Dockerfile
  hack/ccm/Dockerfile
Labels: lgtm, area/provider/ibmcloud, size/XS, cncf-cla: yes, approved

#761 Fix mock client calls in unit tests
  cloud/scope/cluster_test.go
  cloud/scope/machine_test.go
  cloud/scope/powervs_image_test.go
  cloud/scope/powervs_machine_test.go
  controllers/ibmpowervsimage_controller_test.go
  controllers/ibmpowervsmachine_controller_test.go
  controllers/ibmvpccluster_controller_test.go
  controllers/ibmvpcmachine_controller_test.go
Labels: lgtm, area/provider/ibmcloud, size/XL, cncf-cla: yes, approved

#770 upgrade golang bits to be inline with v1.18.x
  .golangci.yml
  controllers/ibmpowervscluster_controller.go
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
  netlify.toml
Labels: lgtm, area/provider/ibmcloud, size/XL, cncf-cla: yes, approved

#773 Bugfix - update gcr.io/k8s-staging-test-infra/gcb-docker-gcloud to latest version
  cloudbuild.yaml
Labels: lgtm, area/provider/ibmcloud, size/XS, cncf-cla: yes, approved

#776 Improve UT coverage for IBMPowerVSCluster controller
  controllers/ibmpowervscluster_controller_test.go
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, size/L, approved

#777 Enhance the print column for powervs resources
  api/v1beta1/ibmpowervscluster_types.go
  api/v1beta1/ibmpowervsmachine_types.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_ibmpowervsclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_ibmpowervsmachines.yaml
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, approved, size/M

#779 Refactor and add VPC variable references
  docs/book/src/topics/vpc/creating-a-cluster.md
Labels: lgtm, area/provider/ibmcloud, size/XS, cncf-cla: yes, approved

#785 Bump gcr.io/kubebuilder/kube-rbac-proxy to v0.13.0
  config/default/manager_auth_proxy_patch.yaml
Labels: lgtm, area/provider/ibmcloud, size/XS, cncf-cla: yes, approved

#786 Bump gcr.io/kubebuilder/kube-rbac-proxy to v0.12.0
  config/default/manager_auth_proxy_patch.yaml
Labels: lgtm, area/provider/ibmcloud, size/XS, cncf-cla: yes, approved

#782 Add unit tests for webhooks
  api/v1beta1/ibmpowervscluster_webhook_test.go
  api/v1beta1/ibmpowervsmachine_webhook_test.go
  api/v1beta1/ibmpowervsmachinetemplate_webhook_test.go
  api/v1beta1/ibmvpcmachine_webhook_test.go
  api/v1beta1/ibmvpcmachinetemplate_webhook_test.go
  api/v1beta1/suite_test.go
Labels: lgtm, area/provider/ibmcloud, size/XXL, cncf-cla: yes, approved

#788 Update the dependencies for the release-0.2
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
  test/e2e/config/ibmcloud-e2e-powervs.yaml
  test/e2e/config/ibmcloud-e2e-vpc.yaml
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, size/L, approved
