Repository kubernetes-sigs/cluster-api-provider-ibmcloud, pull requests merged in 2022-01, with the labels that each got.

#503 Refactor the client code
  Makefile
  cloud/scope/powervs_clients.go
  cloud/scope/powervs_cluster.go
  cloud/scope/powervs_machine.go
  controllers/ibmpowervsmachine_controller.go
  controllers/ibmvpccluster_controller.go
  controllers/ibmvpcmachine_controller.go
  go.mod
  go.sum
  hack/tools/Makefile
  hack/tools/go.mod
  hack/tools/go.sum
  hack/tools/tools.go
  pkg/client.go
  pkg/cloud/services/authenticator/authenticator.go
  pkg/cloud/services/powervs/mock/powervs_generated.go
  pkg/cloud/services/powervs/powervs.go
  pkg/cloud/services/powervs/service.go
  pkg/cloud/services/resourcecontroller/resourcecontroller.go
  pkg/cloud/services/resourcecontroller/service.go
  pkg/cloud/services/utils/accounts.go
Labels: lgtm, area/provider/ibmcloud, size/XL, cncf-cla: yes, approved

#504 Update cluster-api go deps
  go.mod
  go.sum
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, size/L, approved

#505 use controller-gen from hack/tools
  Makefile
  config/crd/bases/infrastructure.cluster.x-k8s.io_ibmpowervsclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_ibmpowervsmachines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_ibmpowervsmachinetemplates.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_ibmvpcclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_ibmvpcmachines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_ibmvpcmachinetemplates.yaml
  config/rbac/role.yaml
  config/webhook/manifests.yaml
  hack/tools/Makefile
  hack/tools/go.mod
  hack/tools/go.sum
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, approved, size/M

#508 Add conditions
  api/v1alpha4/ibmpowervs_conversion.go
  api/v1alpha4/zz_generated.conversion.go
  api/v1beta1/conditions_consts.go
  api/v1beta1/ibmpowervsmachine_types.go
  api/v1beta1/types.go
  api/v1beta1/zz_generated.deepcopy.go
  cloud/scope/powervs_machine.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_ibmpowervsmachines.yaml
  controllers/ibmpowervsmachine_controller.go
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, size/L, approved

#506 Adding e2e test cases
  Makefile
  test/e2e/config/ibmcloud-e2e-powervs.yaml
  test/e2e/config/ibmcloud-e2e-vpc.yaml
  test/e2e/e2e_test.go
  test/e2e/suite_test.go
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, ok-to-test, size/L, approved

#509 Make powervs debug log optional
  cloud/scope/powervs_cluster.go
  cloud/scope/powervs_machine.go
Labels: lgtm, area/provider/ibmcloud, size/XS, cncf-cla: yes, approved

#512 Doc to log requests/responses for powervs apis
  docs/book/src/developer/tilt.md
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, size/S, approved

#511 Add sync-period flag
  cloud/scope/powervs_machine.go
  controllers/ibmpowervsmachine_controller.go
  main.go
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, size/S, approved

#516 Validate OWNERS files - remove sections about emeritus reviewers.
  OWNERS
Labels: lgtm, size/XS, cncf-cla: yes, ok-to-test, approved, kind/cleanup

#517 Bump github.com/IBM-Cloud/power-go-client from 1.0.88 to 1.1.0
  cloud/scope/powervs_cluster.go
  cloud/scope/powervs_machine.go
  go.mod
  go.sum
  pkg/cloud/services/powervs/service.go
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, ok-to-test, approved, size/M

#518 Update cluster-api to v1.1.0-beta.2
  go.mod
  go.sum
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, size/S, approved

#520 Added spzala back to reviewers
  OWNERS
Labels: lgtm, area/provider/ibmcloud, size/XS, cncf-cla: yes, approved

#522 Handle scope creation properly
  cloud/scope/powervs_cluster.go
  cloud/scope/powervs_machine.go
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, size/L, approved

#527 update cluster-api to v1.1.0-rc.0
  go.mod
  go.sum
Labels: lgtm, area/provider/ibmcloud, size/XS, cncf-cla: yes, approved

#523 Fix network/image webhook validations
  api/v1beta1/common.go
  api/v1beta1/ibmpowervscluster_types.go
  api/v1beta1/ibmpowervscluster_webhook.go
  api/v1beta1/ibmpowervsmachine_types.go
  api/v1beta1/ibmpowervsmachine_webhook.go
  api/v1beta1/ibmpowervsmachinetemplate_webhook.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_ibmpowervsclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_ibmpowervsmachines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_ibmpowervsmachinetemplates.yaml
  controllers/ibmpowervscluster_controller_test.go
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, ok-to-test, approved, size/M
