Repository kubernetes-sigs/cluster-api-provider-ibmcloud, pull requests merged in 2022-04, with the labels that each got.

#621 Handle the scope properly
  cloud/scope/powervs_image.go
  go.mod
  go.sum
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, approved, size/M

#622 Fix VPC related issues and minor lint updates
  cloud/scope/cluster.go
  cloud/scope/machine.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_ibmpowervsclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_ibmpowervsimages.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_ibmpowervsmachines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_ibmpowervsmachinetemplates.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_ibmvpcclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_ibmvpcmachines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_ibmvpcmachinetemplates.yaml
  controllers/ibmvpccluster_controller.go
  controllers/ibmvpcmachine_controller.go
  docs/book/src/getting-started.md
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, size/L, approved

#627 Add k8s 1.23.5 image
  docs/book/src/machine-images/powervs.md
Labels: lgtm, area/provider/ibmcloud, size/XS, cncf-cla: yes, approved

#614 Add external Power VS cloud provider support
  docs/book/src/SUMMARY.md
  docs/book/src/topics/powervs/creating-a-cluster.md
  docs/book/src/topics/powervs/external-cloud-provider.md
  hack/ccm/Dockerfile
  hack/ccm/Makefile
  hack/ccm/cloudbuild.yaml
  templates/cluster-template-powervs-cloud-provider.yaml
Labels: lgtm, area/provider/ibmcloud, size/XL, cncf-cla: yes, approved

#630 Fix docker buildx build
  hack/ccm/Makefile
Labels: lgtm, area/provider/ibmcloud, size/XS, cncf-cla: yes, approved

#613 Add Vpc image docs
  docs/book/src/SUMMARY.md
  docs/book/src/topics/vpc/index.md
  docs/book/src/topics/vpc/prerequisites.md
  docs/book/src/topics/vpc/uploading-an-image.md
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, ok-to-test, tide/merge-method-squash, approved, size/M

#631 Update powervs cloud controller image name
  templates/cluster-template-powervs-cloud-provider.yaml
Labels: lgtm, area/provider/ibmcloud, size/XS, cncf-cla: yes, approved

#632 Add events recorder framework
  cloud/scope/cluster.go
  cloud/scope/machine.go
  cloud/scope/powervs_image.go
  cloud/scope/powervs_machine.go
  controllers/ibmpowervscluster_controller.go
  controllers/ibmpowervsimage_controller.go
  controllers/ibmpowervsmachine_controller.go
  controllers/ibmvpccluster_controller.go
  controllers/ibmvpcmachine_controller.go
  go.mod
  main.go
  pkg/record/doc.go
  pkg/record/record.go
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, size/L, approved

#638 Fix URL typo for PowerVS image
  docs/book/src/machine-images/powervs.md
Labels: lgtm, area/provider/ibmcloud, size/XS, cncf-cla: yes, approved

#639 Refine the events
  cloud/scope/powervs_image.go
Labels: lgtm, area/provider/ibmcloud, size/XS, cncf-cla: yes, approved

#635 Add environmetal variable to set providerID format
  cloud/scope/powervs_machine.go
  config/default/manager_auth_proxy_patch.yaml
  config/manager/manager.yaml
  docs/book/src/developer/tilt.md
  docs/book/src/getting-started.md
  main.go
  pkg/options/options.go
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, approved, size/M

#641 Add debug loglevel for E2E runs
  config/manager/manager.yaml
  scripts/ci-e2e.sh
Labels: lgtm, area/provider/ibmcloud, size/XS, cncf-cla: yes, approved

#642 Handle the ERRORED state properly
  api/v1beta1/conditions_consts.go
  api/v1beta1/types.go
  controllers/ibmpowervsmachine_controller.go
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, size/S, approved

#647 update golang version
  Dockerfile
Labels: lgtm, area/provider/ibmcloud, size/XS, cncf-cla: yes, approved

#646 Update the kube-vip to v0.4.4
  templates/cluster-template-powervs-cloud-provider.yaml
  templates/cluster-template-powervs.yaml
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, size/S, approved

#648 Update doc for enabling debug logs
  docs/book/src/getting-started.md
Labels: lgtm, area/provider/ibmcloud, size/XS, cncf-cla: yes, approved

#640 enable debug logs for vpc
  cloud/scope/cluster.go
  cloud/scope/machine.go
Labels: lgtm, area/provider/ibmcloud, size/XS, cncf-cla: yes, approved

#626 Validate machine spec values
  api/v1beta1/common.go
  api/v1beta1/common_test.go
  api/v1beta1/ibmpowervsmachine_types.go
  api/v1beta1/ibmpowervsmachine_webhook.go
  api/v1beta1/ibmpowervsmachinetemplate_webhook.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_ibmpowervsmachines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_ibmpowervsmachinetemplates.yaml
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, size/L, approved
