Repository kubernetes-sigs/cluster-api-provider-ibmcloud, pull requests merged in 2022-03, with the labels that each got.

#582 Add unit tests for Powervs image handling
  cloud/scope/powervs_test.go
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, ok-to-test, approved, size/M

#584 trim whitespace from the ip address
  cloud/scope/powervs_machine.go
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, size/S, approved

#580 Added flag to select ProviderID format for Machine
  api/v1alpha4/zz_generated.conversion.go
  api/v1beta1/ibmpowervsmachine_types.go
  api/v1beta1/zz_generated.deepcopy.go
  cloud/scope/powervs_machine.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_ibmpowervsmachines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_ibmpowervsmachinetemplates.yaml
  controllers/ibmpowervsmachine_controller.go
  main.go
  pkg/options/options.go
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, tide/merge-method-squash, size/L, approved

#586 Update the version matrix
  README.md
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, size/S, approved

#587 Add doc for the images
  docs/book/src/SUMMARY.md
  docs/book/src/machine-images/index.md
  docs/book/src/machine-images/powervs.md
  docs/book/src/machine-images/vpc.md
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, size/S, approved

#590 Update cluster-api to v1.1.3
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
  test/e2e/config/ibmcloud-e2e-powervs.yaml
  test/e2e/config/ibmcloud-e2e-vpc.yaml
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, ok-to-test, approved, size/M

#598 PowerVSImageScope set debug true only if log level set 5 and above
  cloud/scope/powervs_image.go
Labels: lgtm, area/provider/ibmcloud, size/XS, cncf-cla: yes, approved

#601 fix make verify-conversions check
  Makefile
  hack/tools/Makefile
Labels: lgtm, area/provider/ibmcloud, size/XS, cncf-cla: yes, approved

#610 Add note for using provider versions
  docs/book/src/getting-started.md
Labels: lgtm, needs-ok-to-test, area/provider/ibmcloud, size/XS, cncf-cla: yes, approved
