Repository kubernetes-sigs/cluster-api-provider-ibmcloud, pull requests merged in 2022-12, with the labels that each got.

#982 Update cluster-api and ginkgo
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
  test/e2e/config/ibmcloud-e2e-powervs.yaml
  test/e2e/config/ibmcloud-e2e-vpc.yaml
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, approved, size/M

#983 Manage VPC Boot Volume
  api/v1beta1/ibmvpcmachine_types.go
  api/v1beta1/zz_generated.conversion.go
  api/v1beta1/zz_generated.deepcopy.go
  api/v1beta2/common.go
  api/v1beta2/common_test.go
  api/v1beta2/ibmvpcmachine_types.go
  api/v1beta2/ibmvpcmachine_webhook.go
  api/v1beta2/ibmvpcmachine_webhook_test.go
  api/v1beta2/ibmvpcmachinetemplate_webhook.go
  api/v1beta2/webhook.go
  api/v1beta2/zz_generated.deepcopy.go
  cloud/scope/machine.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_ibmvpcmachines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_ibmvpcmachinetemplates.yaml
  controllers/ibmvpcmachine_controller.go
  docs/book/src/topics/vpc/load-balancer.md
  templates/cluster-template-load-balancer.yaml
Labels: lgtm, area/provider/ibmcloud, size/XL, cncf-cla: yes, approved

#984 Refactor the Makefile
  Makefile
  hack/verify-starlark.sh
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, size/L, approved

#985 Add API References
  docs/book/src/SUMMARY.md
  docs/book/src/reference/api-references.md
Labels: lgtm, area/provider/ibmcloud, size/XS, cncf-cla: yes, approved
