Repository kubernetes-sigs/cluster-api-provider-ibmcloud, pull requests merged in 2022-08, with the labels that each got.

#795 Update the golang version to 1.18.5
  Dockerfile
  hack/ccm/Dockerfile
Labels: lgtm, area/provider/ibmcloud, size/XS, cncf-cla: yes, approved

#797 Bump golangci-lint from 1.47.2 to 1.47.3
  controllers/ibmpowervscluster_controller.go
  hack/tools/go.mod
  hack/tools/go.sum
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, approved, size/M

#790 Add apidiff target
  Makefile
  hack/tools/Makefile
  scripts/ci-apidiff.sh
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, approved, size/M

#798 Update prerequisites.md
  docs/book/src/topics/powervs/prerequisites.md
Labels: lgtm, area/provider/ibmcloud, size/XS, cncf-cla: yes, ok-to-test, approved

#802 Integrate MHC for worker nodes with e2e flow
  test/e2e/config/ibmcloud-e2e-powervs.yaml
  test/e2e/data/templates/cluster-template-md-remediation.yaml
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, size/L, approved

#805 Enhance E2E job
  hack/boskos.sh
  scripts/ci-e2e.sh
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, size/S, approved

#808 Fix E2E job failure
  hack/boskos.sh
  scripts/ci-e2e.sh
Labels: lgtm, area/provider/ibmcloud, size/XS, cncf-cla: yes, approved

#809 Update cluster-api to v1.2.1
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
  test/e2e/config/ibmcloud-e2e-powervs.yaml
  test/e2e/config/ibmcloud-e2e-vpc.yaml
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, approved, size/M

#810 Refactor E2E templates generation
  Makefile
  test/e2e/config/ibmcloud-e2e-powervs.yaml
  test/e2e/data/templates/cluster-template-md-remediation.yaml
  test/e2e/data/templates/cluster-template-md-remediation/kustomization.yaml
  test/e2e/data/templates/cluster-template-md-remediation/mhc-powervs.yaml
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, size/L, approved

#823 Update golangci-lint to v1.49.0
  .golangci.yml
  hack/tools/go.mod
  hack/tools/go.sum
  main.go
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, size/L, approved

#817 LoadBalancer integration for VPC
  api/v1alpha3/conversion.go
  api/v1alpha3/zz_generated.conversion.go
  api/v1alpha4/ibmvpc_conversion.go
  api/v1alpha4/zz_generated.conversion.go
  api/v1beta1/conditions_consts.go
  api/v1beta1/ibmvpccluster_types.go
  api/v1beta1/ibmvpcmachine_types.go
  api/v1beta1/types.go
  api/v1beta1/zz_generated.deepcopy.go
  cloud/scope/cluster.go
  cloud/scope/machine.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_ibmvpcclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_ibmvpcmachines.yaml
  controllers/ibmvpccluster_controller.go
  controllers/ibmvpcmachine_controller.go
  pkg/cloud/services/vpc/mock/vpc_generated.go
  pkg/cloud/services/vpc/service.go
  pkg/cloud/services/vpc/vpc.go
Labels: lgtm, area/provider/ibmcloud, size/XL, cncf-cla: yes, approved

#826 Update the go mods
  go.mod
  go.sum
  hack/tools/go.mod
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, size/S, approved
