Repository kubernetes-sigs/cluster-api-provider-ibmcloud, pull requests merged in 2022-09, with the labels that each got.

#837 make SERVICE_ENDPOINT variable optional
  config/manager/manager.yaml
  pkg/endpoints/endpoints.go
  pkg/endpoints/endpoints_test.go
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, size/S, approved

#847 Move label field under config to fix tilt up error
  tilt-provider.json
Labels: lgtm, area/provider/ibmcloud, size/XS, cncf-cla: yes, approved

#846 Remove unwanted logs
  cloud/scope/machine.go
  controllers/ibmpowervsmachine_controller.go
  controllers/ibmvpcmachine_controller.go
Labels: lgtm, area/provider/ibmcloud, size/XS, cncf-cla: yes, approved

#852 Enable additional linters
  .golangci.yml
  pkg/cloud/services/utils/accounts.go
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, size/S, approved

#854 User defined port for the control plane for vpc
  cloud/scope/cluster.go
  controllers/ibmvpccluster_controller.go
  controllers/ibmvpccluster_controller_test.go
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, approved, size/M

#838 Add VPC Load Balancer template
  docs/book/src/SUMMARY.md
  docs/book/src/topics/vpc/load-balancer.md
  templates/cluster-template-load-balancer.yaml
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, size/L, approved

#858 Enhance the gci lint
  .golangci.yml
  api/v1alpha3/conversion.go
  api/v1alpha3/groupversion_info.go
  api/v1alpha3/ibmvpccluster_types.go
  api/v1alpha4/conversion.go
  api/v1alpha4/groupversion_info.go
  api/v1alpha4/ibmpowervs_conversion.go
  api/v1alpha4/ibmpowervscluster_types.go
  api/v1alpha4/ibmvpc_conversion.go
  api/v1alpha4/ibmvpccluster_types.go
  api/v1beta1/groupversion_info.go
  api/v1beta1/ibmpowervscluster_types.go
  api/v1beta1/ibmpowervscluster_webhook.go
  api/v1beta1/ibmpowervsimage_types.go
  api/v1beta1/ibmpowervsimage_webhook.go
  api/v1beta1/ibmpowervsmachine_types.go
  api/v1beta1/ibmpowervsmachine_webhook.go
  api/v1beta1/ibmpowervsmachinetemplate_webhook.go
  api/v1beta1/ibmvpccluster_types.go
  api/v1beta1/ibmvpccluster_webhook.go
  api/v1beta1/ibmvpcmachine_webhook.go
  api/v1beta1/ibmvpcmachinetemplate_webhook.go
  cloud/scope/cluster.go
  cloud/scope/machine.go
  cloud/scope/powervs_cluster.go
  cloud/scope/powervs_image.go
  cloud/scope/powervs_machine.go
  controllers/ibmpowervscluster_controller.go
  controllers/ibmpowervsimage_controller.go
  controllers/ibmpowervsmachine_controller.go
  controllers/ibmvpccluster_controller.go
  controllers/ibmvpcmachine_controller.go
  main.go
  pkg/cloud/services/utils/accounts.go
  pkg/record/record.go
  test/helpers/crd.go
  test/helpers/envtest.go
  util/util.go
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, size/L, approved

#862 Use yaml files for tilt configuration
  docs/book/src/developer/tilt.md
  tilt-provider.json
  tilt-provider.yaml
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, approved, size/M

#867 Update cluster-api to v1.2.2
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
  test/e2e/config/ibmcloud-e2e-powervs.yaml
  test/e2e/config/ibmcloud-e2e-vpc.yaml
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, approved, size/M

#869 Update node selector and toleration for ccm
  hack/ccm/Makefile
  templates/cluster-template-powervs-cloud-provider.yaml
Labels: lgtm, area/provider/ibmcloud, size/XS, cncf-cla: yes, approved

#871 Fix reconcileDelete machine flow for VPC
  cloud/scope/machine.go
  cloud/scope/machine_test.go
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, size/S, approved

#874 Fix go version in the hack/ensure-go.sh script
  hack/ensure-go.sh
Labels: lgtm, area/provider/ibmcloud, size/XS, cncf-cla: yes, approved

#860 Add scale from and to 0 support for autoscaler
  api/v1alpha4/ibmpowervs_conversion.go
  api/v1alpha4/zz_generated.conversion.go
  api/v1beta1/ibmpowervsmachinetemplate_types.go
  api/v1beta1/zz_generated.deepcopy.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_ibmpowervsmachinetemplates.yaml
  config/rbac/role.yaml
  controllers/ibmpowervsmachinetemplate_controller.go
  controllers/ibmpowervsmachinetemplate_controller_test.go
  docs/book/src/SUMMARY.md
  docs/book/src/topics/powervs/autoscaler-scalling-from-0.md
  docs/book/src/topics/powervs/index.md
  main.go
Labels: lgtm, area/provider/ibmcloud, size/XL, cncf-cla: yes, approved

#882 Bump golang to 1.18.6
  Dockerfile
  hack/ccm/Dockerfile
Labels: lgtm, area/provider/ibmcloud, size/XS, cncf-cla: yes, approved

#887 Improve information for the Region/Zone mapping doc
  docs/book/src/reference/regions-zones-mapping.md
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, approved, size/M

#851 Add unit tests for VPC LB integration
  cloud/scope/cluster.go
  cloud/scope/cluster_test.go
  cloud/scope/machine.go
  cloud/scope/machine_test.go
  controllers/ibmvpccluster_controller_test.go
  controllers/ibmvpcmachine_controller.go
  controllers/ibmvpcmachine_controller_test.go
Labels: lgtm, area/provider/ibmcloud, size/XXL, cncf-cla: yes, approved

#894 Fix the ibmcloud cli panic
  scripts/ci-e2e.sh
Labels: lgtm, area/provider/ibmcloud, size/XS, cncf-cla: yes, approved

#884 Organise code blocks in main.go file
  main.go
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, size/L, approved

#900 Publish VPC image for k8s 1.25.2 version
  docs/book/src/machine-images/vpc.md
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, size/S, approved

#895 Update logs as per capi standards
  cloud/scope/powervs_cluster.go
  cloud/scope/powervs_image.go
  cloud/scope/powervs_machine.go
  controllers/ibmpowervscluster_controller.go
  controllers/ibmpowervscluster_controller_test.go
  controllers/ibmpowervsimage_controller.go
  controllers/ibmpowervsimage_controller_test.go
  controllers/ibmpowervsmachine_controller.go
  controllers/ibmpowervsmachinetemplate_controller.go
  controllers/ibmpowervsmachinetemplate_controller_test.go
  main.go
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, size/L, approved

#901 support e2e vpc test flow
  Makefile
  scripts/ci-e2e.sh
  test/e2e/config/ibmcloud-e2e-vpc.yaml
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, size/S, approved
