Repository kubernetes-sigs/cluster-api-provider-ibmcloud, pull requests merged in 2022-02, with the labels that each got.

#528 Add smoke tests
  Dockerfile
  Makefile
  go.mod
  go.sum
  scripts/ci-smoke-test.sh
  test/e2e/config/ibmcloud-e2e-powervs.yaml
  test/e2e/data/shared/metadata.yaml
  test/e2e/suite_test.go
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, ok-to-test, approved, size/M

#507 Add IBMPowerVSImage API
  Dockerfile
  PROJECT
  api/v1beta1/conditions_consts.go
  api/v1beta1/ibmpowervsimage_types.go
  api/v1beta1/ibmpowervsimage_webhook.go
  api/v1beta1/types.go
  api/v1beta1/zz_generated.deepcopy.go
  cloud/scope/powervs_image.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_ibmpowervsimages.yaml
  config/crd/kustomization.yaml
  config/crd/patches/cainjection_in_ibmpowervsimages.yaml
  config/crd/patches/webhook_in_ibmpowervsimages.yaml
  config/rbac/ibmpowervsimage_editor_role.yaml
  config/rbac/ibmpowervsimage_viewer_role.yaml
  config/rbac/role.yaml
  config/samples/infrastructure_v1beta1_ibmpowervsimage.yaml
  config/webhook/manifests.yaml
  controllers/ibmpowervsimage_controller.go
  main.go
  pkg/cloud/services/powervs/service.go
  util/util.go
Labels: lgtm, area/provider/ibmcloud, size/XXL, cncf-cla: yes, ok-to-test, approved

#537 handle image import job properly
  api/v1beta1/conditions_consts.go
  api/v1beta1/ibmpowervsimage_types.go
  api/v1beta1/types.go
  cloud/scope/powervs_image.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_ibmpowervsimages.yaml
  controllers/ibmpowervsimage_controller.go
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, approved, size/M

#536 Add e2e-test script
  .gitignore
  scripts/ci-e2e.sh
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, ok-to-test, approved, size/M

#541 Install kubectl for e2e tests
  Makefile
  scripts/ci-e2e.sh
Labels: lgtm, area/provider/ibmcloud, size/XS, cncf-cla: yes, ok-to-test, approved

#540 Update cluster-api/hack/tools
  hack/tools/go.mod
  hack/tools/go.sum
Labels: lgtm, area/provider/ibmcloud, size/XL, cncf-cla: yes, ok-to-test, approved

#543 Fix IBMPowerVSImage deletion
  controllers/ibmpowervscluster_controller.go
  controllers/ibmpowervsimage_controller.go
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, ok-to-test, size/L, approved

#549 update the deps to latest available version
  Dockerfile
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
Labels: lgtm, area/provider/ibmcloud, size/XL, cncf-cla: yes, approved

#550 Document the release process
  docs/book/src/developer/release.md
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, approved, size/M

#555 Upate cluster-api to v1.1.1
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
  test/e2e/config/ibmcloud-e2e-powervs.yaml
  test/e2e/config/ibmcloud-e2e-vpc.yaml
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, ok-to-test, approved, size/M

#556 Bugfix - Integrate IBMPowerVSImage with MachineSpec
  controllers/ibmpowervsmachine_controller.go
Labels: lgtm, area/provider/ibmcloud, size/XS, cncf-cla: yes, approved

#558 Update delete image flow
  cloud/scope/powervs_image.go
  controllers/ibmpowervsimage_controller.go
  pkg/cloud/services/powervs/service.go
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, size/S, approved

#562 Adding more addresses to the machine spec
  cloud/scope/powervs_machine.go
  controllers/ibmpowervsmachine_controller.go
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, size/S, approved

#565 Use Boskos for proper resource cleanup
  hack/boskos.sh
  scripts/ci-e2e.sh
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, ok-to-test, size/L, approved

#566 Add DeletePolicy to IBMPowerVSImage Spec
  api/v1beta1/ibmpowervsimage_types.go
  api/v1beta1/types.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_ibmpowervsimages.yaml
  controllers/ibmpowervsimage_controller.go
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, approved, size/M

#570 Update cluster-api to v1.1.2
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
  test/e2e/config/ibmcloud-e2e-powervs.yaml
  test/e2e/config/ibmcloud-e2e-vpc.yaml
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, ok-to-test, approved, size/M

#574 Use LocalObjectReference for ImageRef
  api/v1beta1/ibmpowervsmachine_types.go
  api/v1beta1/zz_generated.deepcopy.go
Labels: lgtm, area/provider/ibmcloud, size/XS, cncf-cla: yes, approved

#575 update golang version in the dockerfile
  Dockerfile
Labels: lgtm, area/provider/ibmcloud, size/XS, cncf-cla: yes, approved

#577 Change IBMPowerVSClient type for better mocking
  cloud/scope/powervs_cluster.go
  cloud/scope/powervs_image.go
  cloud/scope/powervs_machine.go
  pkg/cloud/services/powervs/service.go
Labels: lgtm, area/provider/ibmcloud, size/XS, cncf-cla: yes, ok-to-test, approved

#579 Add unit tests for PowerVS
  cloud/scope/powervs_test.go
  cloud/scope/suite_test.go
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, ok-to-test, size/L, approved
