Repository kubernetes-sigs/cluster-api-provider-ibmcloud, pull requests merged in 2022-05, with the labels that each got.

#658 Fix version image shield
  README.md
Labels: lgtm, area/provider/ibmcloud, size/XS, cncf-cla: yes, approved

#660 Fix readme file
  README.md
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, size/S, approved

#659 Add Prajyot-Parab as reviewer
  OWNERS
Labels: lgtm, area/provider/ibmcloud, size/XS, cncf-cla: yes, approved

#664 Register the errors for the powervs vm build failure
  cloud/scope/powervs_machine.go
  controllers/ibmpowervsmachine_controller.go
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, size/S, approved

#652 Expose additional spec params
  docs/book/src/topics/powervs/creating-a-cluster.md
  templates/README.md
  templates/cluster-template-powervs-cloud-provider.yaml
  templates/cluster-template-powervs.yaml
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, approved, size/M

#667 prerequisites for running the unit tests
  Makefile
  hack/tools/Makefile
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, size/S, approved

#671 Update ccm dockerfile to remove building vpcctl binary
  hack/ccm/Dockerfile
  hack/ccm/Makefile
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, size/S, approved

#668 Refactor VPC client code
  cloud/scope/clients.go
  cloud/scope/cluster.go
  cloud/scope/machine.go
  controllers/ibmvpccluster_controller.go
  controllers/ibmvpcmachine_controller.go
  pkg/cloud/services/vpc/doc.go
  pkg/cloud/services/vpc/mock/vpc_generated.go
  pkg/cloud/services/vpc/service.go
  pkg/cloud/services/vpc/vpc.go
Labels: lgtm, area/provider/ibmcloud, size/XL, cncf-cla: yes, approved

#672 Refactor and update Makefiles
  Makefile
  hack/tools/Makefile
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, size/L, approved

#677 Update the golang version
  Dockerfile
Labels: lgtm, area/provider/ibmcloud, size/XS, cncf-cla: yes, approved
