Repository kubernetes-sigs/cluster-api-provider-ibmcloud, pull requests merged in 2022-06, with the labels that each got.

#691 Update cluster-api to 1.1.4
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
  test/e2e/config/ibmcloud-e2e-powervs.yaml
  test/e2e/config/ibmcloud-e2e-vpc.yaml
Labels: lgtm, area/provider/ibmcloud, size/XL, cncf-cla: yes, approved

#680 Support PowerVS custom service endpoints
  cloud/scope/cluster.go
  cloud/scope/machine.go
  cloud/scope/powervs_cluster.go
  cloud/scope/powervs_image.go
  cloud/scope/powervs_machine.go
  config/default/credentials.yaml
  config/manager/manager.yaml
  controllers/ibmpowervscluster_controller.go
  controllers/ibmpowervsimage_controller.go
  controllers/ibmpowervsmachine_controller.go
  controllers/ibmvpccluster_controller.go
  controllers/ibmvpcmachine_controller.go
  docs/book/src/developer/tilt.md
  docs/book/src/getting-started.md
  go.mod
  go.sum
  main.go
  pkg/cloud/services/resourcecontroller/resourcecontroller.go
  pkg/cloud/services/resourcecontroller/service.go
  pkg/endpoints/doc.go
  pkg/endpoints/endpoints.go
  pkg/endpoints/endpoints_test.go
  test/e2e/config/ibmcloud-e2e-powervs.yaml
  test/e2e/config/ibmcloud-e2e-vpc.yaml
Labels: lgtm, area/provider/ibmcloud, size/XL, cncf-cla: yes, approved

#694 Update golang version to 1.17.11
  Dockerfile
  hack/ccm/Dockerfile
Labels: lgtm, area/provider/ibmcloud, size/XS, cncf-cla: yes, approved

#697 Bump golangci-lint to 1.46.2 and Add hack/tools to dependabot
  .github/dependabot.yml
  hack/tools/go.mod
  hack/tools/go.sum
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, size/L, approved

#696 Doc updates
  docs/book/src/topics/powervs/creating-a-cluster.md
  docs/book/src/topics/powervs/external-cloud-provider.md
  docs/book/src/topics/vpc/creating-a-cluster.md
  templates/README.md
Labels: lgtm, area/provider/ibmcloud, size/XS, cncf-cla: yes, approved

#705 Refactor unit test framework
  controllers/ibmpowervscluster_controller_test.go
  controllers/ibmpowervsmachine_controller_test.go
  controllers/suite_test.go
  go.mod
  test/helpers/crd.go
  test/helpers/envtest.go
Labels: lgtm, area/provider/ibmcloud, size/XL, cncf-cla: yes, approved

#716 Add powervs image for k8s 1.24.2
  docs/book/src/machine-images/powervs.md
Labels: lgtm, area/provider/ibmcloud, size/XS, cncf-cla: yes, approved

#709 Add test coverage target to Makefile
  Makefile
  scripts/ci-test-coverage.sh
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, approved, size/M

#717 Bump powervs-utils version
  go.mod
  go.sum
Labels: lgtm, area/provider/ibmcloud, size/XS, cncf-cla: yes, approved

#721 Update cluster-api to v1.2.0-beta.0
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
  test/e2e/config/ibmcloud-e2e-powervs.yaml
  test/e2e/config/ibmcloud-e2e-vpc.yaml
  test/e2e/data/shared/metadata.yaml
Labels: lgtm, area/provider/ibmcloud, size/XL, cncf-cla: yes, approved

#724 Update docker to 1.18 version
  Dockerfile
  hack/ccm/Dockerfile
Labels: lgtm, area/provider/ibmcloud, size/XS, cncf-cla: yes, approved

#730 Update cluster-api to v1.2.0-beta.1
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
  test/e2e/config/ibmcloud-e2e-powervs.yaml
  test/e2e/config/ibmcloud-e2e-vpc.yaml
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, size/L, approved

#732 Update vpc-go-sdk to v0.20.0
  controllers/ibmvpcmachine_controller.go
  go.mod
  go.sum
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, size/S, approved

#733 Update vpc sdk
  controllers/ibmvpcmachine_controller.go
  go.mod
  go.sum
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, size/S, approved

#735 Generate junit xml report for unit tests
  Makefile
  hack/tools/Makefile
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, size/S, approved
