Repository kubernetes-sigs/cluster-api-provider-ibmcloud, pull requests merged in 2023-11, with the labels that each got.

#1470 Update cluster-api to v1.6.0-beta.1
  api/v1beta1/zz_generated.deepcopy.go
  api/v1beta2/zz_generated.deepcopy.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_ibmpowervsclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_ibmpowervsclustertemplates.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_ibmpowervsimages.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_ibmpowervsmachines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_ibmpowervsmachinetemplates.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_ibmvpcclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_ibmvpcmachines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_ibmvpcmachinetemplates.yaml
  config/manager/manager.yaml
  config/rbac/role.yaml
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
  main.go
  test/e2e/config/ibmcloud-e2e-powervs.yaml
  test/e2e/config/ibmcloud-e2e-vpc.yaml
  test/helpers/envtest.go
Labels: lgtm, area/provider/ibmcloud, size/XL, cncf-cla: yes, approved

#1472 Move away from unmaintained packages and repositories.
  cloud/scope/cluster.go
  cloud/scope/cluster_test.go
  cloud/scope/machine.go
  cloud/scope/machine_test.go
  cloud/scope/powervs_cluster.go
  cloud/scope/powervs_image.go
  cloud/scope/powervs_image_test.go
  cloud/scope/powervs_machine.go
  cloud/scope/powervs_machine_test.go
  cmd/capibmadm/cmd/powervs/key/create.go
  cmd/capibmadm/cmd/version/version.go
  cmd/capibmadm/cmd/vpc/key/create.go
  controllers/ibmpowervscluster_controller.go
  controllers/ibmpowervsimage_controller.go
  controllers/ibmpowervsimage_controller_test.go
  controllers/ibmpowervsmachine_controller.go
  controllers/ibmpowervsmachine_controller_test.go
  controllers/ibmvpccluster_controller.go
  controllers/ibmvpccluster_controller_test.go
  controllers/ibmvpcmachine_controller.go
  controllers/ibmvpcmachine_controller_test.go
  go.mod
  go.sum
  hack/tools/Makefile
  hack/tools/go.mod
  hack/tools/go.sum
  hack/tools/tools.go
  pkg/cloud/services/powervs/mock/powervs_generated.go
  pkg/cloud/services/utils/paging.go
  pkg/cloud/services/vpc/mock/vpc_generated.go
  test/helpers/envtest.go
  util/util.go
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, ok-to-test, size/L, approved

#1476 Update test metadata.yaml with cluster-api v1.6
  test/e2e/data/shared/metadata.yaml
Labels: lgtm, area/provider/ibmcloud, size/XS, cncf-cla: yes, approved

#1473 PROVIDER_ID_FORMAT references replacement.
  README.md
  docs/book/src/developer/tilt.md
  docs/book/src/getting-started.md
  docs/book/src/topics/powervs/clusterclass-cluster.md
  docs/book/src/topics/powervs/external-cloud-provider.md
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, ok-to-test, approved, size/M

#1486 [release-0.6] add targets for verifying code and images for vulnerabilities
  Dockerfile
  Makefile
  hack/ccm/Dockerfile
  hack/tools/Makefile
  hack/tools/go.mod
  hack/tools/go.sum
  hack/tools/tools.go
  hack/verify-container-images.sh
Labels: lgtm, area/provider/ibmcloud, size/XXL, cncf-cla: yes, approved

#1489 Fix CVE-2023-47108 Vulnerability
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, approved, size/M

#1487 [release-0.5] add targets for verifying code and images for vulnerabilities
  Dockerfile
  Makefile
  controllers/ibmpowervscluster_controller.go
  hack/ccm/Dockerfile
  hack/tools/Makefile
  hack/tools/go.mod
  hack/tools/go.sum
  hack/tools/tools.go
  hack/verify-container-images.sh
Labels: lgtm, area/provider/ibmcloud, size/XXL, cncf-cla: yes, approved

#1501 Update doc commands with correct template references
  docs/book/src/topics/vpc/load-balancer.md
Labels: lgtm, area/provider/ibmcloud, size/XS, cncf-cla: yes, approved

#1500 Add support for VPC clusterclass
  Makefile
  PROJECT
  api/v1beta2/ibmvpcclustertemplate_types.go
  api/v1beta2/zz_generated.deepcopy.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_ibmvpcclustertemplates.yaml
  config/crd/kustomization.yaml
  config/crd/patches/cainjection_in_ibmvpcclustertemplates.yaml
  config/crd/patches/webhook_in_ibmvpcclustertemplates.yaml
  config/rbac/ibmvpcclustertemplate_editor_role.yaml
  config/rbac/ibmvpcclustertemplate_viewer_role.yaml
  docs/book/src/SUMMARY.md
  docs/book/src/getting-started.md
  docs/book/src/topics/vpc/clusterclass-cluster.md
  docs/book/src/topics/vpc/index.md
  templates/cluster-template-vpc-clusterclass.yaml
  templates/cluster-template-vpc-clusterclass/cluster-with-kcp.yaml
  templates/cluster-template-vpc-clusterclass/kustomization.yaml
  templates/cluster-template-vpc-clusterclass/md.yaml
Labels: lgtm, area/provider/ibmcloud, size/XL, cncf-cla: yes, ok-to-test, approved

#1504 Add documentation for E2E testing
  docs/book/src/SUMMARY.md
  docs/book/src/developer/e2e.md
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, approved, size/M

#1503 Bump golang from 1.20.10 to 1.20.11
  Dockerfile
  Makefile
  hack/ccm/Dockerfile
Labels: lgtm, area/provider/ibmcloud, size/XS, cncf-cla: yes, approved

#1509 Update cluster-api to v1.6.0-rc.0
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
  test/e2e/config/ibmcloud-e2e-powervs.yaml
  test/e2e/config/ibmcloud-e2e-vpc.yaml
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, size/L, approved

#1512 Check if controllers are deployed successfully in smoke-test
  test/e2e/suite_test.go
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, size/S, approved

#1513 Fix the finalizer code
  controllers/ibmpowervscluster_controller.go
  controllers/ibmpowervsimage_controller.go
  controllers/ibmpowervsimage_controller_test.go
  controllers/ibmpowervsmachine_controller.go
  controllers/ibmpowervsmachine_controller_test.go
  controllers/ibmvpccluster_controller.go
  controllers/ibmvpcmachine_controller.go
  controllers/ibmvpcmachine_controller_test.go
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, size/S, approved

#1508 Streamline documentation for CAPIBM
  docs/book/src/SUMMARY.md
  docs/book/src/developer/index.md
  docs/book/src/developer/tilt-with-podman.md
  docs/book/src/developer/tilt.md
  docs/book/src/getting-started.md
  docs/book/src/machine-images/index.md
  docs/book/src/reference/reference.md
  docs/book/src/topics/index.md
  docs/book/src/topics/vpc/index.md
Labels: lgtm, cncf-cla: yes, ok-to-test, size/L, approved

#1519 Publish PVS and VPC image for k8s 1.28.4 version
  docs/book/src/machine-images/powervs.md
  docs/book/src/machine-images/vpc.md
Labels: lgtm, area/provider/ibmcloud, size/XS, cncf-cla: yes, approved

#1518 Update cluster-api to v1.6.0-rc.1
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
  test/e2e/config/ibmcloud-e2e-powervs.yaml
  test/e2e/config/ibmcloud-e2e-vpc.yaml
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, approved, size/M
