Repository kubernetes-sigs/cluster-api-provider-ibmcloud, pull requests merged in 2023-08, with the labels that each got.

#1321 [Release-0.4] update kubebuilder tools to 1.25.x
  Makefile
  scripts/fetch_ext_bins.sh
Labels: lgtm, area/provider/ibmcloud, size/XS, cncf-cla: yes, approved

#1322 [Release-0.5] Fix k8s version of kubebuilder tools
  scripts/fetch_ext_bins.sh
Labels: lgtm, area/provider/ibmcloud, size/XS, cncf-cla: yes, approved

#1323 Fix k8s version of kubebuilder tools
  scripts/fetch_ext_bins.sh
Labels: lgtm, area/provider/ibmcloud, size/XS, cncf-cla: yes, approved

#1324 Refactor the getting started guide
  docs/book/src/getting-started.md
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, approved, size/M

#1327 [release-0.4] Refactor the getting started guide
  docs/book/src/getting-started.md
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, approved, size/M

#1329 [release-0.4] book: update refs to release specific books
  docs/book/book.toml
  docs/book/src/introduction.md
  docs/book/theme/css/custom.css
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, approved, size/M

#1330 update dependencies list with IBM packages
  docs/book/src/developer/dependencies.md
Labels: lgtm, area/provider/ibmcloud, size/XS, cncf-cla: yes, approved

#1339 disable KCP remediation
  test/e2e/data/templates/cluster-template-powervs-md-remediation/kustomization.yaml
Labels: lgtm, area/provider/ibmcloud, size/XS, cncf-cla: yes, approved

#1342 Bump github.com/IBM-Cloud/power-go-client from 1.2.4 to 1.3.0
  cmd/capibmadm/cmd/powervs/network/list.go
  go.mod
  go.sum
Labels: lgtm, area/provider/ibmcloud, size/XS, cncf-cla: yes, approved

#1343 add v0.5.x to compatibility matrix
  README.md
Labels: lgtm, area/provider/ibmcloud, size/XS, cncf-cla: yes, approved

#1356 Restructure dependency page for better readability
  docs/book/src/developer/dependencies.md
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, approved, size/M

#1357 Enable retry of ibmcloud login command to avoid timeout failure
  scripts/ci-e2e.sh
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, size/S, approved

#1362 Set REGION var only if BOSKOS_REGION is not nil
  scripts/ci-e2e.sh
Labels: lgtm, area/provider/ibmcloud, size/XS, cncf-cla: yes, approved

#1364 E2E fixes
  scripts/ci-e2e.sh
  templates/addons/crs.yaml
  templates/cluster-template-vpc-load-balancer.yaml
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, size/S, approved

#1367 Fix netlify redirects
  netlify.toml
Labels: lgtm, area/provider/ibmcloud, size/XS, cncf-cla: yes, approved

#1370 Drop release-0.3 from book docs
  docs/book/src/introduction.md
Labels: lgtm, area/provider/ibmcloud, size/XS, cncf-cla: yes, approved

#1372 Add document to configure podman to use tilt
  Makefile
  docs/book/src/SUMMARY.md
  docs/book/src/developer/tilt-with-podman.md
  hack/kind-install.sh
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, size/L, approved

#1379 Run generate-templates as a part of make generate
  Makefile
Labels: lgtm, area/provider/ibmcloud, size/XS, cncf-cla: yes, approved

#1378 [Release-0.5] Update cluster-api to v1.4.6
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
  test/e2e/config/ibmcloud-e2e-powervs.yaml
  test/e2e/config/ibmcloud-e2e-vpc.yaml
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, size/L, approved

#1377 Update cluster-api to v1.5.1
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
  test/e2e/config/ibmcloud-e2e-powervs.yaml
  test/e2e/config/ibmcloud-e2e-vpc.yaml
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, approved, size/M
