Repository kubernetes-sigs/cluster-api-provider-ibmcloud, pull requests merged in 2023-12, with the labels that each got.

#1528 Update cluster-api to v1.6.0
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
  scripts/ci-e2e.sh
  test/e2e/config/ibmcloud-e2e-powervs.yaml
  test/e2e/config/ibmcloud-e2e-vpc.yaml
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, approved, size/M

#1530 [release-0.5] Update cluster-api to v1.4.9
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
  test/e2e/config/ibmcloud-e2e-powervs.yaml
  test/e2e/config/ibmcloud-e2e-vpc.yaml
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, size/L, approved

#1531 [release-0.5] Update e2e tooling/image bits
  scripts/ci-e2e.sh
Labels: lgtm, area/provider/ibmcloud, size/XS, cncf-cla: yes, approved

#1520 Add support and release content to CAPIBM book doc
  docs/book/src/SUMMARY.md
  docs/book/src/developer/index.md
  docs/book/src/developer/release-support-guidelines.md
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, ok-to-test, approved, size/M

#1539 Bump github.com/aquasecurity/trivy from 0.47.0 to 0.48.0
  hack/tools/go.mod
  hack/tools/go.sum
Labels: lgtm, area/provider/ibmcloud, size/XL, cncf-cla: yes, approved

#1542 Bump golang to v1.20.12
  Dockerfile
  Makefile
  hack/ccm/Dockerfile
Labels: lgtm, area/provider/ibmcloud, size/XS, cncf-cla: yes, approved

#1544 [release-0.5] Bump golang to v1.20.12
  Dockerfile
  Makefile
  hack/ccm/Dockerfile
Labels: lgtm, area/provider/ibmcloud, size/XS, cncf-cla: yes, approved

#1546 Update version references to 0.7.0
  metadata.yaml
  test/e2e/config/ibmcloud-e2e-powervs.yaml
  test/e2e/config/ibmcloud-e2e-vpc.yaml
Labels: lgtm, area/provider/ibmcloud, size/XS, cncf-cla: yes, approved

#1549 Update release versions in security scan workflow
  .github/workflows/weekly-security-scan.yaml
  README.md
Labels: lgtm, area/provider/ibmcloud, size/XS, cncf-cla: yes, approved

#1548 Bump capibm images to k8s 1.28.x for e2e flow
  scripts/ci-e2e.sh
  test/e2e/config/ibmcloud-e2e-powervs.yaml
  test/e2e/config/ibmcloud-e2e-vpc.yaml
Labels: lgtm, area/provider/ibmcloud, size/XS, cncf-cla: yes, approved

#1553 Remove deprecated --short flag
  hack/ensure-kubectl.sh
Labels: lgtm, area/provider/ibmcloud, size/XS, cncf-cla: yes, approved
