Repository kubernetes-sigs/cluster-api-provider-ibmcloud, pull requests merged in 2023-06, with the labels that each got.

#1250 Modify capibmadm to not use GetAPIKeyDetails to fetch the account ID
  cmd/capibmadm/cmd/powervs/image/import.go
  cmd/capibmadm/cmd/powervs/image/list.go
  cmd/capibmadm/cmd/powervs/key/create.go
  cmd/capibmadm/cmd/powervs/key/delete.go
  cmd/capibmadm/cmd/powervs/key/list.go
  cmd/capibmadm/cmd/powervs/network/create.go
  cmd/capibmadm/cmd/powervs/network/delete.go
  cmd/capibmadm/cmd/powervs/network/list.go
  cmd/capibmadm/cmd/powervs/port/create.go
  cmd/capibmadm/cmd/powervs/port/delete.go
  cmd/capibmadm/cmd/powervs/port/list.go
  cmd/capibmadm/cmd/vpc/image/list.go
  cmd/capibmadm/cmd/vpc/key/create.go
  cmd/capibmadm/cmd/vpc/key/list.go
  cmd/capibmadm/utils/utils.go
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, approved, size/M

#1256 Build and use capibmadm from main for E2E
  .gitignore
  scripts/ci-e2e.sh
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, size/S, approved

#1259 Update Dockerfile syntax to 1.5
  Dockerfile
  Makefile
  hack/boilerplate/boilerplate.Dockerfile.txt
  hack/ccm/Dockerfile
Labels: lgtm, area/provider/ibmcloud, size/XS, cncf-cla: yes, approved

#1261 Update cluster-api to v1.4.3
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
  test/e2e/config/ibmcloud-e2e-powervs.yaml
  test/e2e/config/ibmcloud-e2e-vpc.yaml
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, approved, size/M

#1273 fix book image banner
  docs/book/src/images/k8s-ibm-cloud.png
  docs/book/src/introduction.md
Labels: lgtm, area/provider/ibmcloud, size/XS, cncf-cla: yes, approved
