Repository kubernetes-sigs/cluster-api-provider-ibmcloud, pull requests merged in 2023-07, with the labels that each got.

#1275 add supported iaas info of IBM Cloud
  docs/book/src/images/ibm-cloud-iaas.png
  docs/book/src/introduction.md
Labels: lgtm, area/provider/ibmcloud, size/XS, cncf-cla: yes, approved

#1274 Update golang, k8s and cluster-api
  .golangci.yml
  api/v1beta2/ibmpowervscluster_webhook.go
  api/v1beta2/ibmpowervsclustertemplate_webhook.go
  api/v1beta2/ibmpowervsclustertemplate_webhook_test.go
  api/v1beta2/ibmpowervsimage_webhook.go
  api/v1beta2/ibmpowervsmachine_webhook.go
  api/v1beta2/ibmpowervsmachinetemplate_webhook.go
  api/v1beta2/ibmvpccluster_webhook.go
  api/v1beta2/ibmvpcmachine_webhook.go
  api/v1beta2/ibmvpcmachinetemplate_webhook.go
  cmd/capibmadm/cmd/powervs/image/import.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_ibmpowervsclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_ibmpowervsclustertemplates.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_ibmpowervsimages.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_ibmpowervsmachines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_ibmpowervsmachinetemplates.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_ibmvpcclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_ibmvpcmachines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_ibmvpcmachinetemplates.yaml
  go.mod
  go.sum
  hack/ensure-go.sh
  hack/tools/Makefile
  hack/tools/go.mod
  hack/tools/go.sum
  hack/tools/tools.go
  netlify.toml
  test/e2e/config/ibmcloud-e2e-powervs.yaml
  test/e2e/config/ibmcloud-e2e-vpc.yaml
  test/e2e/data/shared/metadata.yaml
Labels: lgtm, area/provider/ibmcloud, size/XL, cncf-cla: yes, approved

#1278 Publish PVS and VPC image for k8s 1.27.2 version
  docs/book/src/machine-images/powervs.md
  docs/book/src/machine-images/vpc.md
Labels: lgtm, area/provider/ibmcloud, size/XS, cncf-cla: yes, approved

#1280 Use k8s 1.27.2 images for e2e tests
  scripts/ci-e2e.sh
  test/e2e/config/ibmcloud-e2e-powervs.yaml
  test/e2e/config/ibmcloud-e2e-vpc.yaml
Labels: lgtm, area/provider/ibmcloud, size/XS, cncf-cla: yes, approved

#1289 Update cluster-api to v1.5.0-rc.0
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
  test/e2e/config/ibmcloud-e2e-powervs.yaml
  test/e2e/config/ibmcloud-e2e-vpc.yaml
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, size/L, approved

#1296 Update KIND to v0.20.0
  hack/ensure-kind.sh
Labels: lgtm, area/provider/ibmcloud, size/XS, cncf-cla: yes, approved

#1297 update kubebuilder tools to 1.27.x
  Makefile
Labels: lgtm, area/provider/ibmcloud, size/XS, cncf-cla: yes, approved

#1299 Update dependencies
  Makefile
  go.mod
  go.sum
  hack/ensure-kind.sh
  hack/ensure-kubectl.sh
  hack/tools/go.mod
  hack/tools/go.sum
  test/e2e/config/ibmcloud-e2e-powervs.yaml
  test/e2e/config/ibmcloud-e2e-vpc.yaml
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, approved, size/M

#1288 book: update refs to release specific books
  docs/book/book.toml
  docs/book/src/introduction.md
  docs/book/theme/css/custom.css
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, approved, size/M

#1308 cleanup unused files
  Makefile
  hack/ensure-kustomize.sh
  hack/kind-install-for-capd.sh
  hack/pin-dependency.sh
  hack/setup-envtest-with-kind.sh
  hack/verify-doctoc.sh
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, size/L, approved

#1302 Add unit test for record.go
  pkg/record/record_test.go
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, ok-to-test, size/L, approved

#1307 fix machine reconciliation bug
  api/v1beta2/conditions_consts.go
  cloud/scope/powervs_machine.go
  cloud/scope/powervs_machine_test.go
  controllers/ibmpowervsmachine_controller.go
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, approved, size/M

#1312 Update cluster-api to v1.5.0
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
  test/e2e/config/ibmcloud-e2e-powervs.yaml
  test/e2e/config/ibmcloud-e2e-vpc.yaml
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, approved, size/M

#1314 [release-0.5] Update cluster-api to v1.4.5
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
  test/e2e/config/ibmcloud-e2e-powervs.yaml
  test/e2e/config/ibmcloud-e2e-vpc.yaml
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, approved, size/M

#1315 fix build tags
  hack/tools/Makefile
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, size/S, approved

#1319 [release-0.5] fix build tags
  hack/tools/Makefile
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, size/S, approved

#1317 [release-0.4] Fix build tags and Bump golangci-lint to v1.51.0
  hack/tools/Makefile
  hack/tools/go.mod
  hack/tools/go.sum
  hack/tools/tools.go
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, size/L, approved

#1313 [release-0.4] Update cluster-api to v1.3.10
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
  test/e2e/config/ibmcloud-e2e-powervs.yaml
  test/e2e/config/ibmcloud-e2e-vpc.yaml
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, size/L, approved
