Repository kubernetes-sigs/cluster-api-provider-ibmcloud, pull requests merged in 2023-10, with the labels that each got.

#1434 Update cluster-api to v1.5.2
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
  test/e2e/config/ibmcloud-e2e-powervs.yaml
  test/e2e/config/ibmcloud-e2e-vpc.yaml
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, approved, size/M

#1437 [release-0.5] Update cluster-api to v1.4.7
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
  test/e2e/config/ibmcloud-e2e-powervs.yaml
  test/e2e/config/ibmcloud-e2e-vpc.yaml
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, approved, size/M

#1440 Update golang to 1.20.9
  Dockerfile
  hack/ccm/Dockerfile
Labels: lgtm, area/provider/ibmcloud, size/XS, cncf-cla: yes, approved

#1441 fix: remove trailing whitespace from metadata.yaml
  metadata.yaml
Labels: lgtm, area/provider/ibmcloud, size/XS, cncf-cla: yes, approved

#1443 [release-0.5] fix: remove trailing whitespace from metadata.yaml
  metadata.yaml
Labels: lgtm, area/provider/ibmcloud, size/XS, cncf-cla: yes, approved

#1458 Replace gopkg.in/yaml.v2 with sigs.k8s.io/yaml
  cmd/capibmadm/cmd/version/version.go
  go.mod
Labels: lgtm, area/provider/ibmcloud, size/XS, cncf-cla: yes, ok-to-test, approved, kind/cleanup

#1454 Update the go deps
  go.mod
  go.sum
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, size/L, approved

#1463 Bump golangci-lint and make it happy
  cloud/scope/cluster.go
  cloud/scope/cluster_test.go
  cloud/scope/powervs_image_test.go
  cloud/scope/powervs_machine.go
  cloud/scope/powervs_machine_test.go
  hack/tools/go.mod
  hack/tools/go.sum
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, size/L, approved

#1466 Bump golang from 1.20.9 to 1.20.10
  Dockerfile
  hack/ccm/Dockerfile
Labels: lgtm, area/provider/ibmcloud, size/XS, cncf-cla: yes, approved

#1422 Add targets for verifying code and images for vulnerabilities
  .github/workflows/weekly-security-scan.yaml
  Makefile
  hack/tools/Makefile
  hack/tools/go.mod
  hack/tools/go.sum
  hack/tools/tools.go
  hack/verify-container-images.sh
Labels: lgtm, area/provider/ibmcloud, size/XXL, cncf-cla: yes, approved

#1468 [release-0.6] Update cluster-api to v1.5.3 and bump related deps
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
  test/e2e/config/ibmcloud-e2e-powervs.yaml
  test/e2e/config/ibmcloud-e2e-vpc.yaml
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, size/L, approved

#1467 [release-0.5] Update cluster-api to v1.4.8 and bump related deps
  cmd/capibmadm/cmd/powervs/network/list.go
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
  test/e2e/config/ibmcloud-e2e-powervs.yaml
  test/e2e/config/ibmcloud-e2e-vpc.yaml
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, size/L, approved
