Repository kubernetes-sigs/cluster-api-provider-ibmcloud, pull requests merged in 2023-01, with the labels that each got.

#1014 Update cluster-api to v1.3.1
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
  test/e2e/config/ibmcloud-e2e-powervs.yaml
  test/e2e/config/ibmcloud-e2e-vpc.yaml
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, size/L, approved

#989 Add support for SSHKey and Image names (VPC)
  api/v1beta1/ibmvpc_conversion.go
  api/v1beta1/ibmvpcmachine_types.go
  api/v1beta1/zz_generated.conversion.go
  api/v1beta1/zz_generated.deepcopy.go
  api/v1beta2/ibmvpcmachine_types.go
  api/v1beta2/ibmvpcmachine_webhook_test.go
  api/v1beta2/zz_generated.deepcopy.go
  cloud/scope/machine.go
  cloud/scope/machine_test.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_ibmvpcmachines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_ibmvpcmachinetemplates.yaml
  controllers/ibmvpcmachine_controller_test.go
  docs/book/src/topics/vpc/creating-a-cluster.md
  docs/book/src/topics/vpc/load-balancer.md
  pkg/cloud/services/vpc/mock/vpc_generated.go
  pkg/cloud/services/vpc/service.go
  pkg/cloud/services/vpc/vpc.go
  scripts/ci-e2e.sh
  templates/README.md
  templates/cluster-template-load-balancer.yaml
  templates/cluster-template.yaml
  test/e2e/config/ibmcloud-e2e-vpc.yaml
Labels: lgtm, area/provider/ibmcloud, size/XL, cncf-cla: yes, approved

#1025 Update cluster-api to v1.3.2
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
  test/e2e/config/ibmcloud-e2e-powervs.yaml
  test/e2e/config/ibmcloud-e2e-vpc.yaml
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, approved, size/M

#1015 Add external cloud provider support for VPC
  cloud/scope/machine.go
  cloud/scope/powervs_machine.go
  config/manager/manager.yaml
  controllers/ibmvpcmachine_controller.go
  docs/book/src/SUMMARY.md
  docs/book/src/developer/tilt.md
  docs/book/src/getting-started.md
  docs/book/src/topics/powervs/external-cloud-provider.md
  docs/book/src/topics/vpc/load-balancer.md
  main.go
  pkg/cloud/services/utils/accounts.go
  pkg/options/options.go
  templates/cluster-template-load-balancer.yaml
  templates/cluster-template-powervs-cloud-provider.yaml
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, size/L, approved

#1026 Integrate running VPC e2e tests with Boskos
  hack/boskos.sh
  scripts/ci-e2e.sh
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, size/S, approved

#1033 Fix the delete subnet flow
  cloud/scope/cluster.go
  cloud/scope/cluster_test.go
  controllers/ibmvpccluster_controller_test.go
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, approved, size/M

#1032 Changes to deprecate powervs-provider-id-fmt flat
  cloud/scope/powervs_machine.go
  main.go
  pkg/options/options.go
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, size/S, approved

#1035 Phase 1 - Refactor PowerVS Machine Spec
  api/v1beta1/ibmpowervs_conversion.go
  api/v1beta1/zz_generated.conversion.go
  api/v1beta2/common.go
  api/v1beta2/common_test.go
  api/v1beta2/ibmpowervsmachine_types.go
  api/v1beta2/ibmpowervsmachine_webhook.go
  api/v1beta2/ibmpowervsmachine_webhook_test.go
  api/v1beta2/ibmpowervsmachinetemplate_webhook.go
  api/v1beta2/ibmpowervsmachinetemplate_webhook_test.go
  api/v1beta2/zz_generated.deepcopy.go
  cloud/scope/powervs_machine.go
  cloud/scope/powervs_machine_test.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_ibmpowervsmachines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_ibmpowervsmachinetemplates.yaml
  controllers/ibmpowervsmachine_controller_test.go
  controllers/ibmpowervsmachinetemplate_controller.go
  controllers/ibmpowervsmachinetemplate_controller_test.go
  templates/cluster-template-powervs-cloud-provider.yaml
  templates/cluster-template-powervs.yaml
  templates/cluster-template-simple-powervs-clusterclass.yaml
Labels: lgtm, area/provider/ibmcloud, size/XL, cncf-cla: yes, tide/merge-method-squash, approved

#1030 Proposal for capibmadm cli tool
  docs/proposal/20230113-capibm-cli-tool.md
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, size/L, approved

#1041 Update golang to 1.19.5
  Dockerfile
  hack/ccm/Dockerfile
Labels: lgtm, area/provider/ibmcloud, size/XS, cncf-cla: yes, approved

#1042 Minor spec comments update
  api/v1beta2/ibmpowervsmachine_types.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_ibmpowervsmachines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_ibmpowervsmachinetemplates.yaml
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, size/S, approved

#1044 Update golang to 1.18.10
  Dockerfile
  api/v1beta1/suite_test.go
  cloud/scope/suite_test.go
  hack/ccm/Dockerfile
Labels: lgtm, area/provider/ibmcloud, size/XS, cncf-cla: yes, approved

#1045 Update Go Modules
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
  test/e2e/config/ibmcloud-e2e-powervs.yaml
  test/e2e/config/ibmcloud-e2e-vpc.yaml
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, size/L, approved

#1046 Update Kubernetes version for PowerVS e2e
  scripts/ci-e2e.sh
  test/e2e/config/ibmcloud-e2e-powervs.yaml
Labels: lgtm, area/provider/ibmcloud, size/XS, cncf-cla: yes, approved

#1043 Minor e2e fixes
  Makefile
  api/v1beta1/ibmvpccluster_types.go
  api/v1beta2/ibmvpccluster_types.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_ibmvpcclusters.yaml
  scripts/ci-e2e.sh
  templates/cluster-template-vpc-load-balancer.yaml
  test/e2e/config/ibmcloud-e2e-powervs.yaml
  test/e2e/config/ibmcloud-e2e-vpc.yaml
  test/e2e/data/templates/cluster-template-powervs-md-remediation/kustomization.yaml
  test/e2e/data/templates/cluster-template-powervs-md-remediation/mhc-powervs.yaml
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, approved, size/M

#1027 Add initial code for capibmadm tool
  cmd/capibmadm/cmd/doc.go
  cmd/capibmadm/cmd/powervs/doc.go
  cmd/capibmadm/cmd/powervs/network/create.go
  cmd/capibmadm/cmd/powervs/network/doc.go
  cmd/capibmadm/cmd/powervs/network/network.go
  cmd/capibmadm/cmd/powervs/powervs.go
  cmd/capibmadm/cmd/root.go
  cmd/capibmadm/main.go
  cmd/capibmadm/options/doc.go
  cmd/capibmadm/options/options.go
  docs/book/src/SUMMARY.md
  docs/book/src/topics/capibmadm/index.md
  docs/book/src/topics/capibmadm/powervs/index.md
  docs/book/src/topics/capibmadm/powervs/network.md
  go.mod
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, size/L, approved

#1057 Minor e2e related fixes
  scripts/ci-e2e.sh
  test/e2e/config/ibmcloud-e2e-vpc.yaml
  test/e2e/data/cni/calico/calico.yaml
Labels: lgtm, area/provider/ibmcloud, size/XS, cncf-cla: yes, approved

#1053 Implement paging mechaism
  cloud/scope/cluster.go
  cloud/scope/machine.go
  pkg/cloud/services/utils/paging.go
Labels: lgtm, area/provider/ibmcloud, size/XL, cncf-cla: yes, approved

#1062 Fix environment variable IBMCLOUD_API_KEY assigment
  docs/book/src/topics/vpc/load-balancer.md
Labels: lgtm, area/provider/ibmcloud, size/XS, cncf-cla: yes, approved

#1063 update compatibility matrix
  README.md
Labels: lgtm, area/provider/ibmcloud, size/XS, cncf-cla: yes, approved

#1064 Migrate away from google.com gcp project k8s-testimages
  cloudbuild.yaml
  hack/ccm/cloudbuild.yaml
Labels: lgtm, area/provider/ibmcloud, size/XS, cncf-cla: yes, approved
