Repository kubernetes-sigs/cluster-api-provider-ibmcloud, pull requests merged in 2024-06, with the labels that each got.

#1819 Derive VPC zones from VPC region instead of PowerVS region.
  cloud/scope/powervs_cluster.go
  util/util.go
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, size/S, ok-to-test, approved

#1812 Update log format while checking the state of a resource
  api/v1beta2/types.go
  cloud/scope/powervs_cluster.go
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, approved, size/M

#1746 Add validation for loadbalancer port against 6443 and to avoid duplicate names
  api/v1beta2/ibmpowervscluster_webhook.go
  api/v1beta2/ibmvpccluster_types.go
  cloud/scope/powervs_cluster.go
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, ok-to-test, approved, size/M

#1820 Set TerminationMessagePolicy to FallbackToLogsOnError
  config/manager/manager.yaml
  templates/addons/crs-powervs.yaml
  templates/addons/crs.yaml
  templates/cluster-template-powervs-cloud-provider.yaml
  templates/cluster-template-powervs-clusterclass.yaml
  templates/cluster-template-powervs-create-infra.yaml
  templates/cluster-template-vpc-clusterclass.yaml
  templates/cluster-template.yaml
  test/e2e/data/templates/cluster-template-vpc.yaml
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, ok-to-test, approved, size/M

#1834 Add webhook validation for transit gateway's global routing field
  api/v1beta2/ibmpowervscluster_webhook.go
  cloud/scope/powervs_cluster.go
  cloud/scope/powervs_machine.go
  cloud/scope/util.go
  controllers/ibmpowervscluster_controller.go
  controllers/ibmpowervsimage_controller.go
  controllers/ibmpowervsmachine_controller.go
  go.mod
  go.sum
  util/util.go
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, size/L, approved

#1842 Fix trivy analysis reported issues
  Makefile
Labels: lgtm, area/provider/ibmcloud, size/XS, cncf-cla: yes, approved

#1843 update kubebuilder tools to 1.29.3
  Makefile
  scripts/fetch_ext_bins.sh
Labels: lgtm, area/provider/ibmcloud, size/XS, cncf-cla: yes, approved

#1840 Update cluster-api to v1.7.3
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
  test/e2e/config/ibmcloud-e2e-powervs.yaml
  test/e2e/config/ibmcloud-e2e-vpc.yaml
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, approved, size/M

#1825 Improve IBMPowerVSCluster deletion
  cloud/scope/powervs_cluster.go
  cloud/scope/types.go
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, approved, size/M

#1841 [release-0.7]Update cluster-api to v1.6.6
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
  test/e2e/config/ibmcloud-e2e-powervs.yaml
  test/e2e/config/ibmcloud-e2e-vpc.yaml
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, approved, size/M

#1844 [release-0.7]update kubebuilder tools to 1.28.x
  Makefile
  scripts/fetch_ext_bins.sh
Labels: lgtm, area/provider/ibmcloud, size/XS, cncf-cla: yes, approved

#1845 [release-0.7]Fix trivy analysis reported issues
  Makefile
Labels: lgtm, area/provider/ibmcloud, size/XS, cncf-cla: yes, approved

#1853 Use zone to filter PowerVS service instance
  api/v1beta2/ibmpowervscluster_types.go
  cloud/scope/powervs_cluster.go
  cloud/scope/powervs_image.go
  cloud/scope/powervs_machine.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_ibmpowervsclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_ibmpowervsclustertemplates.yaml
  controllers/ibmpowervsimage_controller.go
  pkg/cloud/services/resourcecontroller/resourcecontroller.go
  pkg/cloud/services/resourcecontroller/service.go
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, approved, size/M
