Repository kubernetes-sigs/cluster-api-provider-ibmcloud, pull requests merged in 2024-03, with the labels that each got.

#1633 [release-0.6] Update cluster-api to v1.5.6
  Dockerfile
  Makefile
  go.mod
  go.sum
  hack/ccm/Dockerfile
  hack/ensure-go.sh
  hack/tools/go.mod
  hack/tools/go.sum
  test/e2e/config/ibmcloud-e2e-powervs.yaml
  test/e2e/config/ibmcloud-e2e-vpc.yaml
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, size/L, approved

#1641 [release-0.7] Update cluster-api to v1.6.2
  Dockerfile
  go.mod
  go.sum
  hack/ccm/Dockerfile
  hack/ensure-go.sh
  hack/tools/go.mod
  hack/tools/go.sum
  test/e2e/config/ibmcloud-e2e-powervs.yaml
  test/e2e/config/ibmcloud-e2e-vpc.yaml
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, size/L, approved

#1649 Update api specs and comments.
  docs/proposal/20231109-powervs-infra-creation.md
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, approved, size/M

#1652 Support service instance id in ibmpowervsmachine reconcilation
  api/v1beta2/ibmpowervscluster_webhook.go
  cloud/scope/powervs_machine.go
Labels: lgtm, area/provider/ibmcloud, size/XS, cncf-cla: yes, approved

#1656 Configure private or public loadbalancer
  api/v1beta2/ibmpowervscluster_types.go
  api/v1beta2/ibmvpccluster_types.go
  cloud/scope/powervs_cluster.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_ibmpowervsclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_ibmpowervsclustertemplates.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_ibmvpcclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_ibmvpcclustertemplates.yaml
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, approved, size/M

#1658 Update loadbalancer spec to configure private loadbalncer
  api/v1beta2/ibmvpccluster_types.go
  api/v1beta2/zz_generated.deepcopy.go
  cloud/scope/powervs_cluster.go
  cloud/scope/powervs_machine.go
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, size/S, approved

#1677 Update OWNERS
  OWNERS
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, size/S, approved

#1671 Update cluster-api to v1.7.0-beta.0
  api/v1beta2/ibmpowervscluster_webhook_test.go
  api/v1beta2/ibmpowervsmachine_webhook_test.go
  api/v1beta2/ibmpowervsmachinetemplate_webhook_test.go
  cloud/scope/cluster.go
  cloud/scope/cluster_test.go
  cloud/scope/machine.go
  cloud/scope/machine_test.go
  cloud/scope/powervs_cluster.go
  cloud/scope/powervs_image.go
  cloud/scope/powervs_image_test.go
  cloud/scope/powervs_machine.go
  cloud/scope/powervs_machine_test.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_ibmpowervsclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_ibmpowervsclustertemplates.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_ibmpowervsimages.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_ibmpowervsmachines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_ibmpowervsmachinetemplates.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_ibmvpcclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_ibmvpcclustertemplates.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_ibmvpcmachines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_ibmvpcmachinetemplates.yaml
  controllers/ibmpowervscluster_controller_test.go
  controllers/ibmpowervsimage_controller_test.go
  controllers/ibmpowervsmachine_controller_test.go
  controllers/ibmpowervsmachinetemplate_controller_test.go
  controllers/ibmvpccluster_controller_test.go
  controllers/ibmvpcmachine_controller_test.go
  controllers/ibmvpcmachinetemplate_controller_test.go
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
  main.go
  metadata.yaml
  pkg/cloud/services/resourcecontroller/service.go
  pkg/cloud/services/transitgateway/service.go
  test/e2e/config/ibmcloud-e2e-powervs.yaml
  test/e2e/config/ibmcloud-e2e-vpc.yaml
  test/e2e/data/shared/metadata.yaml
  test/e2e/e2e_test.go
  test/helpers/crd.go
  test/helpers/envtest.go
Labels: lgtm, area/provider/ibmcloud, size/XXL, cncf-cla: yes, approved

#1682 Use uncached client
  controllers/ibmpowervscluster_controller.go
  controllers/ibmpowervscluster_controller_test.go
  main.go
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, size/S, approved

#1664 Fix cos flow
  api/v1beta2/ibmpowervscluster_webhook.go
  api/v1beta2/types.go
  cloud/scope/powervs_cluster.go
  cloud/scope/powervs_machine.go
  controllers/ibmpowervscluster_controller.go
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, size/L, approved

#1688 Remove COS instance spec check in webhook
  api/v1beta2/ibmpowervscluster_webhook.go
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, size/S, approved

#1691 Support service instance id for IBMPowerVSImage
  cloud/scope/powervs_image.go
Labels: lgtm, area/provider/ibmcloud, size/XS, cncf-cla: yes, approved

#1692 Explicitly set GVK for IBMPoweVSCluster resource
  controllers/ibmpowervscluster_controller.go
  controllers/ibmpowervscluster_controller_test.go
  main.go
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, approved, size/M

#1694 Update cluster-api to v1.7.0-beta.1
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
  test/e2e/config/ibmcloud-e2e-powervs.yaml
  test/e2e/config/ibmcloud-e2e-vpc.yaml
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, size/L, approved

#1695 [release-0.7] Update cluster-api to v1.6.3
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
  test/e2e/config/ibmcloud-e2e-powervs.yaml
  test/e2e/config/ibmcloud-e2e-vpc.yaml
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, approved, size/M

#1696 [release-0.6] Update cluster-api to v1.5.7
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
  test/e2e/config/ibmcloud-e2e-powervs.yaml
  test/e2e/config/ibmcloud-e2e-vpc.yaml
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, approved, size/M
