Repository kubernetes-sigs/cluster-api-provider-ibmcloud, pull requests merged in 2024-07, with the labels that each got.

#1861 Use cloud-provider template for PowerVS e2e by default
  scripts/ci-e2e.sh
  test/e2e/data/templates/cluster-template-powervs-md-remediation.yaml
  test/e2e/data/templates/cluster-template-powervs-md-remediation/kustomization.yaml
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, size/L, approved

#1863 PowerVS CI: configure public network creation with specific DNS servers
  scripts/ci-e2e.sh
Labels: lgtm, area/provider/ibmcloud, size/XS, cncf-cla: yes, approved

#1865 Enhance the instructions for PowerVS image build with DHCP support
  docs/book/src/developer/build-images.md
  docs/book/src/machine-images/powervs.md
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, size/S, approved

#1827 Refactor PowerVSClusterscope function to faciliate UT integration
  cloud/scope/powervs_cluster.go
  cloud/scope/powervs_cluster_test.go
  controllers/ibmpowervscluster_controller.go
  controllers/ibmpowervscluster_controller_test.go
  pkg/cloud/services/powervs/service.go
  pkg/cloud/services/resourcecontroller/service.go
Labels: lgtm, area/provider/ibmcloud, size/XL, cncf-cla: yes, approved

#1870 Update troubleshooting guide
  docs/book/src/user/troubleshooting.md
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, approved, size/M

#1878 Update cluster-api to v1.7.4
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
  test/e2e/config/ibmcloud-e2e-powervs.yaml
  test/e2e/config/ibmcloud-e2e-vpc.yaml
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, approved, size/M

#1880 Update golang version to 1.21.12
  Makefile
  hack/ccm/Makefile
Labels: lgtm, area/provider/ibmcloud, size/XS, cncf-cla: yes, approved

#1879 [release-0.7]Update cluster-api to v1.6.7
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
  test/e2e/config/ibmcloud-e2e-powervs.yaml
  test/e2e/config/ibmcloud-e2e-vpc.yaml
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, approved, size/M

#1875 VPC: Extend VPC API's to support v2 Infra
  api/v1beta1/ibmvpc_conversion.go
  api/v1beta1/zz_generated.conversion.go
  api/v1beta2/ibmvpccluster_types.go
  api/v1beta2/zz_generated.deepcopy.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_ibmvpcclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_ibmvpcclustertemplates.yaml
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, ok-to-test, size/L, approved

#1860 Use the COS endpoint override when generating bootstrap ignition
  cloud/scope/powervs_machine.go
Labels: lgtm, area/provider/ibmcloud, size/XS, cncf-cla: yes, ok-to-test, approved

#1858 VPC: Create v2 path for new Infrastructure implementation
  cloud/scope/vpc_cluster.go
  controllers/ibmvpccluster_controller.go
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, ok-to-test, size/L, approved

#1883 VPC: Extend VPC related API's for v2 VPC reconcile
  api/v1beta1/zz_generated.conversion.go
  api/v1beta2/ibmvpccluster_types.go
  api/v1beta2/types.go
  api/v1beta2/zz_generated.deepcopy.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_ibmvpcclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_ibmvpcclustertemplates.yaml
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, ok-to-test, size/L, approved

#1897 Deprecate provider-id format v1
  config/manager/manager.yaml
  docs/book/src/topics/powervs/clusterclass-cluster.md
  docs/book/src/topics/powervs/create-resources.md
  docs/book/src/topics/powervs/external-cloud-provider.md
  docs/book/src/topics/vpc/load-balancer.md
  main.go
  pkg/options/options.go
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, size/S, ok-to-test, approved

#1899 Print kubebuilder assets downloaded location
  Makefile
Labels: lgtm, area/provider/ibmcloud, size/XS, cncf-cla: yes, approved

#1900 Minor changes to e2e flow
  scripts/ci-e2e.sh
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, size/S, approved
