Repository kubernetes-sigs/cluster-api-provider-ibmcloud, pull requests merged in 2024-02, with the labels that each got.

#1488 Add proposal for Power VS infra creation
  docs/images/powervs-cluster-components.excalidraw
  docs/images/powervs-cluster-components.png
  docs/images/powervs-cluster-create-workflow.excalidraw
  docs/images/powervs-cluster-create-workflow.png
  docs/images/powervs-cluster-delete-workflow.excalidraw
  docs/images/powervs-cluster-delete-workflow.png
  docs/proposal/20231109-powervs-infra-creation.md
Labels: lgtm, area/provider/ibmcloud, size/XXL, cncf-cla: yes, approved

#1584 Replaced pvsadm image import reference with capibmadm powervs image import
  docs/book/src/topics/capibmadm/index.md
  docs/book/src/topics/powervs/prerequisites.md
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, size/S, ok-to-test, approved

#1605 Update cloud-provider-powervs commit to create latest ccm image
  hack/ccm/Makefile
Labels: lgtm, area/provider/ibmcloud, size/XS, cncf-cla: yes, approved

#1606 Update tempaltes to use latest ccm image
  templates/addons/crs-powervs.yaml
  templates/addons/crs.yaml
  templates/cluster-template-powervs-cloud-provider.yaml
  templates/cluster-template-powervs-clusterclass.yaml
  templates/cluster-template-vpc-clusterclass.yaml
  templates/cluster-template.yaml
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, size/S, approved

#1522 Makefile and other visual changes.
  Dockerfile
  Makefile
  README.md
  docs/book/theme/favicon.png
  hack/ccm/Dockerfile
  hack/ccm/Makefile
  versions.mk
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, ok-to-test, approved, size/M

#1523 Scale from and to 0 support for autoscaler for VPC cluster
  api/v1beta1/ibmvpc_conversion.go
  api/v1beta1/ibmvpcmachinetemplate_types.go
  api/v1beta1/zz_generated.conversion.go
  api/v1beta1/zz_generated.deepcopy.go
  api/v1beta2/ibmvpcmachinetemplate_types.go
  api/v1beta2/zz_generated.deepcopy.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_ibmvpcmachinetemplates.yaml
  config/rbac/role.yaml
  controllers/ibmvpcmachinetemplate_controller.go
  controllers/ibmvpcmachinetemplate_controller_test.go
  main.go
  pkg/cloud/services/vpc/mock/vpc_generated.go
  pkg/cloud/services/vpc/service.go
  pkg/cloud/services/vpc/vpc.go
Labels: lgtm, area/provider/ibmcloud, size/XL, cncf-cla: yes, ok-to-test, approved

#1612 Tag power-iaas plugin to a specific version
  scripts/ci-e2e.sh
Labels: lgtm, area/provider/ibmcloud, size/XS, cncf-cla: yes, approved

#1614 [release-0.6]Tag power-iaas plugin to a specific version
  scripts/ci-e2e.sh
Labels: lgtm, area/provider/ibmcloud, size/XS, cncf-cla: yes, approved

#1613 [release-0.7]Tag power-iaas plugin to a specific version
  scripts/ci-e2e.sh
Labels: lgtm, area/provider/ibmcloud, size/XS, cncf-cla: yes, approved

#1627 Update api specs as per new changes
  docs/proposal/20231109-powervs-infra-creation.md
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, approved, size/M

#1632 Update cluster-api to v1.6.2
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
  test/e2e/config/ibmcloud-e2e-powervs.yaml
  test/e2e/config/ibmcloud-e2e-vpc.yaml
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, approved, size/M
