Repository kubernetes-sigs/cluster-api-provider-ibmcloud, pull requests merged in 2024-01, with the labels that each got.

#1566 Bump go.uber.org/mock from 0.3.0 to 0.4.0 in /hack/tools
  hack/tools/go.mod
  hack/tools/go.sum
  pkg/cloud/services/powervs/mock/powervs_generated.go
  pkg/cloud/services/vpc/mock/vpc_generated.go
Labels: lgtm, area/provider/ibmcloud, size/XS, cncf-cla: yes, approved

#1572 book: update refs to release-0-7 specific book
  docs/book/src/introduction.md
Labels: lgtm, area/provider/ibmcloud, size/XS, cncf-cla: yes, approved

#1573 [release-0.6] Add support and release content to CAPIBM book doc
  docs/book/src/SUMMARY.md
  docs/book/src/developer/index.md
  docs/book/src/developer/release-support-guidelines.md
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, approved, size/M

#1575 Update release support data
  docs/book/src/developer/release-support-guidelines.md
Labels: lgtm, area/provider/ibmcloud, size/XS, cncf-cla: yes, approved

#1586 [release-0.6] Update cluster-api to v1.5.5
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
  test/e2e/config/ibmcloud-e2e-powervs.yaml
  test/e2e/config/ibmcloud-e2e-vpc.yaml
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, approved, size/M

#1588 [release-0.7] Update cluster-api to v1.6.1
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
  test/e2e/config/ibmcloud-e2e-powervs.yaml
  test/e2e/config/ibmcloud-e2e-vpc.yaml
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, approved, size/M

#1485 API changes to support infra creation
  api/v1beta1/ibmpowervs_conversion.go
  api/v1beta1/ibmvpc_conversion.go
  api/v1beta1/zz_generated.conversion.go
  api/v1beta2/ibmpowervscluster_types.go
  api/v1beta2/ibmpowervsimage_types.go
  api/v1beta2/ibmpowervsmachine_types.go
  api/v1beta2/ibmvpccluster_types.go
  api/v1beta2/types.go
  api/v1beta2/zz_generated.deepcopy.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_ibmpowervsclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_ibmpowervsclustertemplates.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_ibmpowervsimages.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_ibmpowervsmachines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_ibmpowervsmachinetemplates.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_ibmvpcclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_ibmvpcclustertemplates.yaml
Labels: lgtm, area/provider/ibmcloud, size/XXL, cncf-cla: yes, approved

#1592 Update api specs
  api/v1beta1/zz_generated.conversion.go
  api/v1beta2/ibmpowervscluster_types.go
  api/v1beta2/ibmvpccluster_types.go
  api/v1beta2/zz_generated.deepcopy.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_ibmpowervsclusters.yaml
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, approved, size/M

#1596 Replace service with worskpace after power-iaas plugin update
  scripts/ci-e2e.sh
Labels: lgtm, area/provider/ibmcloud, size/XS, cncf-cla: yes, approved
