Repository kubernetes-sigs/cluster-api-provider-ibmcloud, pull requests merged in 2024-04, with the labels that each got.

#1693 Avoid returning error when resource creation and deletion is in progress
  api/v1beta2/types.go
  cloud/scope/powervs_cluster.go
  controllers/ibmpowervscluster_controller.go
Labels: lgtm, area/provider/ibmcloud, size/XL, cncf-cla: yes, approved

#1669 VPC: Add Security Group resources and constants/enums
  api/v1beta2/types.go
  api/v1beta2/zz_generated.deepcopy.go
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, ok-to-test, size/L, approved

#1698 Fix security exposure
  hack/boskos.sh
  hack/kind-network-fix.sh
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, size/S, approved

#1701 Update cluster-api to v1.7.0-rc.0
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
  test/e2e/config/ibmcloud-e2e-powervs.yaml
  test/e2e/config/ibmcloud-e2e-vpc.yaml
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, approved, size/M

#1702 Fix trivy analysis reported issues
  Makefile
  hack/tools/go.mod
  hack/tools/go.sum
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, size/S, approved

#1714 Validate DHCP network id
  cloud/scope/powervs_machine.go
Labels: lgtm, area/provider/ibmcloud, size/XS, cncf-cla: yes, approved

#1710 Fix kubebuilder validation for SecurityGroup resources
  api/v1beta2/types.go
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, size/S, ok-to-test, approved

#1722 Update cluster-api to v1.7.0-rc.1
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
  test/e2e/config/ibmcloud-e2e-powervs.yaml
  test/e2e/config/ibmcloud-e2e-vpc.yaml
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, approved, size/M

#1715 Add lowercase regex validation for vpc, vpcsubnet and loadbalancer names
  api/v1beta2/ibmpowervscluster_types.go
  api/v1beta2/ibmvpccluster_types.go
  api/v1beta2/types.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_ibmpowervsclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_ibmpowervsclustertemplates.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_ibmvpcclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_ibmvpcclustertemplates.yaml
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, ok-to-test, approved, size/M

#1723 bump golang to v1.21.9
  Makefile
  hack/ccm/Makefile
Labels: lgtm, area/provider/ibmcloud, size/XS, cncf-cla: yes, approved

#1703 [release-0.6] bump golang to v1.21.9
  Dockerfile
  Makefile
  hack/ccm/Dockerfile
Labels: lgtm, area/provider/ibmcloud, size/XS, cncf-cla: yes, approved

#1704 [release-0.7] bump golang to v1.21.9
  Dockerfile
  Makefile
  hack/ccm/Dockerfile
Labels: lgtm, area/provider/ibmcloud, size/XS, cncf-cla: yes, approved

#1728 Use user provided vpc subnetid
  cloud/scope/powervs_cluster.go
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, size/S, approved

#1740 Refactor resource manager to use interface and override resource manager endpoint URL
  cloud/scope/powervs_cluster.go
  pkg/cloud/services/resourcemanager/doc.go
  pkg/cloud/services/resourcemanager/resourcemanager.go
  pkg/cloud/services/resourcemanager/service.go
  pkg/endpoints/endpoints.go
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, size/L, approved

#1735 [release-0.7]Update go mod dependencies
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
  test/e2e/config/ibmcloud-e2e-powervs.yaml
  test/e2e/config/ibmcloud-e2e-vpc.yaml
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, size/L, approved

#1736 [release-0.6]Update go mod dependencies
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
  test/e2e/config/ibmcloud-e2e-powervs.yaml
  test/e2e/config/ibmcloud-e2e-vpc.yaml
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, size/L, approved

#1734 Update cluster-api to v1.7.0
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
  test/e2e/config/ibmcloud-e2e-powervs.yaml
  test/e2e/config/ibmcloud-e2e-vpc.yaml
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, size/L, approved

#1739 Add custom type for resource not found error
  cloud/scope/powervs_cluster.go
  cloud/scope/types.go
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, approved, size/M

#1750 Ignore updating github.com/IBM/networking-go-sdk until we move to go 1.22
  .github/dependabot.yml
Labels: lgtm, area/provider/ibmcloud, size/XS, cncf-cla: yes, approved
