Repository kubernetes-sigs/cluster-api-provider-ibmcloud, pull requests merged in 2024-05, with the labels that each got.

#1753 Update cluster-api to v1.7.1
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
  test/e2e/config/ibmcloud-e2e-powervs.yaml
  test/e2e/config/ibmcloud-e2e-vpc.yaml
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, approved, size/M

#1733 Verify if ID is present before using it
  cloud/scope/powervs_cluster.go
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, size/S, approved

#1756 Update PowerVS image builder document
  docs/book/src/developer/build-images.md
Labels: lgtm, area/provider/ibmcloud, size/XS, cncf-cla: yes, approved

#1768 Rearrange main.go and use same context for manager and controller
  controllers/ibmpowervscluster_controller.go
  controllers/ibmvpccluster_controller.go
  main.go
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, size/L, approved

#1752 Update PortRange and ICMP types for Security Groups
  api/v1beta2/types.go
  api/v1beta2/zz_generated.deepcopy.go
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, size/S, ok-to-test, approved

#1778 User klog.Background() instead of textlogger
  cloud/scope/cluster.go
  cloud/scope/cluster_test.go
  cloud/scope/machine.go
  cloud/scope/machine_test.go
  cloud/scope/powervs_cluster.go
  cloud/scope/powervs_image.go
  cloud/scope/powervs_image_test.go
  cloud/scope/powervs_machine.go
  cloud/scope/powervs_machine_test.go
  controllers/ibmpowervscluster_controller_test.go
  controllers/ibmpowervsimage_controller_test.go
  controllers/ibmpowervsmachine_controller_test.go
  controllers/ibmvpccluster_controller_test.go
  controllers/ibmvpcmachine_controller_test.go
  main.go
  test/helpers/envtest.go
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, size/L, approved

#1775 Refactor IsPowerVSZoneSupportsPER() code to use interface
  cloud/scope/powervs_cluster.go
  pkg/cloud/services/powervs/mock/powervs_generated.go
  pkg/cloud/services/powervs/powervs.go
  pkg/cloud/services/powervs/service.go
Labels: lgtm, cncf-cla: yes, ok-to-test, tide/merge-method-squash, approved, size/M

#1787 Bump k8s version to 1.29 in e2e for VPC
  docs/book/src/machine-images/vpc.md
  scripts/ci-e2e.sh
  test/e2e/config/ibmcloud-e2e-vpc.yaml
Labels: lgtm, area/provider/ibmcloud, size/XS, cncf-cla: yes, approved

#1785 skip load balancer pool member deletion if instance creation fails
  cloud/scope/machine.go
Labels: lgtm, area/provider/ibmcloud, size/XS, cncf-cla: yes, approved

#1776 Update deletion logic for VPC subnet, load balancer and PowerVS service instance
  cloud/scope/powervs_cluster.go
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, approved, size/M

#1783 Rename VPC security group types
  api/v1beta2/types.go
  api/v1beta2/zz_generated.deepcopy.go
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, size/L, approved

#1738 Support VPC security group for PowerVS clusters
  api/v1beta1/zz_generated.conversion.go
  api/v1beta2/conditions_consts.go
  api/v1beta2/ibmpowervscluster_types.go
  api/v1beta2/ibmvpccluster_types.go
  api/v1beta2/types.go
  api/v1beta2/zz_generated.deepcopy.go
  cloud/scope/powervs_cluster.go
  cloud/scope/types.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_ibmpowervsclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_ibmpowervsclustertemplates.yaml
  controllers/ibmpowervscluster_controller.go
  pkg/cloud/services/vpc/mock/vpc_generated.go
  pkg/cloud/services/vpc/service.go
  pkg/cloud/services/vpc/vpc.go
Labels: lgtm, area/provider/ibmcloud, size/XXL, cncf-cla: yes, approved

#1777 Use local routing in transit gateway when PowerVS and VPC are from same region
  api/v1beta2/ibmpowervscluster_types.go
  api/v1beta2/zz_generated.deepcopy.go
  cloud/scope/powervs_cluster.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_ibmpowervsclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_ibmpowervsclustertemplates.yaml
  util/util.go
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, approved, size/M

#1755 Refactor logging
  api/v1beta2/ibmpowervscluster_types.go
  cloud/scope/powervs_cluster.go
  cloud/scope/powervs_machine.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_ibmpowervsclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_ibmpowervsclustertemplates.yaml
  controllers/ibmpowervscluster_controller.go
  controllers/ibmpowervsmachine_controller.go
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, size/L, approved

#1791 Bump golang to v1.21.10
  Makefile
  hack/ccm/Makefile
Labels: lgtm, area/provider/ibmcloud, size/XS, cncf-cla: yes, approved

#1794 fix: remove whitespaces from metadata.yaml
  metadata.yaml
Labels: lgtm, area/provider/ibmcloud, size/XS, cncf-cla: yes, approved

#1797 fix: remove whitespaces from metadata.yaml
  metadata.yaml
Labels: lgtm, area/provider/ibmcloud, size/XS, cncf-cla: yes, approved

#1800 Update version references to 0.9.0
  metadata.yaml
  test/e2e/config/ibmcloud-e2e-powervs.yaml
  test/e2e/config/ibmcloud-e2e-vpc.yaml
Labels: lgtm, area/provider/ibmcloud, size/XS, cncf-cla: yes, approved

#1801 [release-0.7]Update cluster-api to v1.6.5
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
  test/e2e/config/ibmcloud-e2e-powervs.yaml
  test/e2e/config/ibmcloud-e2e-vpc.yaml
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, approved, size/M

#1803 Update release versions for weekly security scan
  .github/workflows/weekly-security-scan.yaml
Labels: lgtm, area/provider/ibmcloud, size/XS, cncf-cla: yes, approved

#1810 Ignore updating github.com/aquasecurity/trivy until we move to go 1.22
  .github/dependabot.yml
Labels: lgtm, area/provider/ibmcloud, size/XS, cncf-cla: yes, approved

#1798 Update kube-vip spec in cluster templates to adopt k8s 1.29
  Makefile
  templates/bases/powervs/kcp.yaml
  templates/cluster-template-powervs-cloud-provider.yaml
  templates/cluster-template-powervs-clusterclass.yaml
  templates/cluster-template-powervs-clusterclass/cluster-with-kcp.yaml
  templates/cluster-template-powervs.yaml
  test/e2e/data/templates/cluster-template-powervs-md-remediation.yaml
  test/e2e/data/templates/cluster-template-vpc.yaml
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, size/L, approved

#1799 Bump PowerVS CI to k8s v1.29
  docs/book/src/machine-images/powervs.md
  scripts/ci-e2e.sh
  test/e2e/config/ibmcloud-e2e-powervs.yaml
Labels: lgtm, area/provider/ibmcloud, size/XS, cncf-cla: yes, approved

#1816 Fetch service instance id from spec of IBMPowerVSCluster object while setting provider id
  cloud/scope/powervs_machine.go
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, size/S, approved
