Repository kubernetes-sigs/cluster-api-provider-ibmcloud, pull requests merged in 2024-12, with the labels that each got.

#2079 Set toolchain in go.mod
  go.mod
  hack/tools/go.mod
Labels: lgtm, needs-ok-to-test, area/provider/ibmcloud, size/XS, cncf-cla: yes, approved

#2083 Update release support data
  docs/book/src/developer/e2e.md
  docs/book/src/developer/release-support-guidelines.md
Labels: lgtm, area/provider/ibmcloud, size/XS, cncf-cla: yes, approved

#2088 [release-0.8] Update release support data
  docs/book/src/developer/e2e.md
  docs/book/src/developer/release-support-guidelines.md
Labels: lgtm, area/provider/ibmcloud, size/XS, cncf-cla: yes, approved

#2092 [release-0.9] Update docs with references to release-0.9
  README.md
  docs/book/src/introduction.md
Labels: lgtm, area/provider/ibmcloud, size/XS, cncf-cla: yes, approved

#2082 Update docs with references to release-0.9
  README.md
  docs/book/src/introduction.md
Labels: lgtm, area/provider/ibmcloud, size/XS, cncf-cla: yes, approved

#2069 Update cluster-api to v1.9.x
  Makefile
  api/v1beta1/ibmpowervsmachine_types.go
  api/v1beta1/zz_generated.conversion.go
  api/v1beta1/zz_generated.deepcopy.go
  api/v1beta2/ibmpowervsmachine_types.go
  api/v1beta2/ibmvpcmachine_types.go
  api/v1beta2/types.go
  api/v1beta2/zz_generated.deepcopy.go
  cloud/scope/machine.go
  cloud/scope/powervs_machine.go
  cloud/scope/powervs_machine_test.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_ibmpowervsclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_ibmpowervsclustertemplates.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_ibmpowervsimages.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_ibmpowervsmachines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_ibmpowervsmachinetemplates.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_ibmvpcclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_ibmvpcclustertemplates.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_ibmvpcmachines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_ibmvpcmachinetemplates.yaml
  config/rbac/role.yaml
  controllers/ibmpowervscluster_controller.go
  controllers/ibmpowervsmachine_controller.go
  controllers/ibmvpccluster_controller.go
  controllers/ibmvpcmachine_controller.go
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
  scripts/fetch_ext_bins.sh
  test/e2e/config/ibmcloud-e2e-powervs.yaml
  test/e2e/config/ibmcloud-e2e-vpc.yaml
  test/e2e/data/shared/metadata.yaml
Labels: lgtm, area/provider/ibmcloud, size/XXL, cncf-cla: yes, approved

#2093 [release-0.8] Update docs with references to release-0.8
  docs/book/src/introduction.md
Labels: lgtm, area/provider/ibmcloud, size/XS, cncf-cla: yes, approved

#2094 Update cluster-api to v1.9.0-rc.1
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
  test/e2e/config/ibmcloud-e2e-powervs.yaml
  test/e2e/config/ibmcloud-e2e-vpc.yaml
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, approved, size/M

#2095 Bumped go.mod version in tools
  hack/tools/go.mod
Labels: lgtm, area/provider/ibmcloud, size/XS, cncf-cla: yes, ok-to-test, tide/merge-method-squash, approved

#2099 bump gcr.io/k8s-staging-test-infra/gcb-docker-gcloud to v20241111-71c32dbdcc
  cloudbuild.yaml
  hack/ccm/cloudbuild.yaml
Labels: lgtm, area/provider/ibmcloud, size/XS, cncf-cla: yes, approved

#2100 Modify the expect check for aggregate errors
  controllers/ibmpowervscluster_controller_test.go
Labels: lgtm, area/provider/ibmcloud, size/XS, cncf-cla: yes, ok-to-test, approved

#2105 Pin to working golang and gcb-docker-gcloud version
  cloudbuild.yaml
  hack/tools/go.mod
Labels: lgtm, area/provider/ibmcloud, size/XS, cncf-cla: yes, approved

#2112 Update cluster-api to v1.9.3
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
  test/e2e/config/ibmcloud-e2e-powervs.yaml
  test/e2e/config/ibmcloud-e2e-vpc.yaml
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, approved, size/M

#2111 [release-0.9] Update cluster-api to v1.8.8
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
  test/e2e/config/ibmcloud-e2e-powervs.yaml
  test/e2e/config/ibmcloud-e2e-vpc.yaml
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, size/L, approved

#2110 [release-0.8] Update cluster-api to v1.7.9
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
  test/e2e/config/ibmcloud-e2e-powervs.yaml
  test/e2e/config/ibmcloud-e2e-vpc.yaml
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, size/L, approved
