Repository kubernetes-sigs/cluster-api-provider-ibmcloud, pull requests merged in 2024-08, with the labels that each got.

#1903 [release-0.7] Update golang version to 1.21.12
  Dockerfile
  Makefile
  hack/ccm/Dockerfile
Labels: lgtm, area/provider/ibmcloud, size/XS, cncf-cla: yes, approved

#1904 [release-0.8] Update cluster-api to v1.7.4
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
  test/e2e/config/ibmcloud-e2e-powervs.yaml
  test/e2e/config/ibmcloud-e2e-vpc.yaml
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, approved, size/M

#1913 Generate mocks for all the IBM Cloud services
  pkg/cloud/services/cos/cos.go
  pkg/cloud/services/cos/mock/cos_generated.go
  pkg/cloud/services/globaltagging/globaltagging.go
  pkg/cloud/services/globaltagging/mock/globaltagging_generated.go
  pkg/cloud/services/resourcecontroller/mock/resourcecontroller_generated.go
  pkg/cloud/services/resourcecontroller/resourcecontroller.go
  pkg/cloud/services/resourcemanager/mock/resourcemanager_generated.go
  pkg/cloud/services/resourcemanager/resourcemanager.go
  pkg/cloud/services/transitgateway/mock/transitgateway_generated.go
  pkg/cloud/services/transitgateway/transitgateway.go
  pkg/cloud/services/vpc/vpc.go
Labels: lgtm, area/provider/ibmcloud, size/XL, cncf-cla: yes, approved

#1918 Remove kube-rbac-proxy
  config/default/kustomization.yaml
  config/default/manager_auth_proxy_patch.yaml
  config/manager/manager.yaml
  config/rbac/auth_proxy_client_clusterrole.yaml
  config/rbac/auth_proxy_role.yaml
  config/rbac/auth_proxy_role_binding.yaml
  config/rbac/auth_proxy_service.yaml
  config/rbac/kustomization.yaml
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, approved, size/M

#1802 Update docs with references to release-0.8
  README.md
  docs/book/src/introduction.md
Labels: lgtm, area/provider/ibmcloud, size/XS, cncf-cla: yes, approved

#1925 [release-0.8]Update cluster-api to v1.7.5 and golang to 1.21.13
  Makefile
  go.mod
  go.sum
  hack/ccm/Makefile
  hack/tools/go.mod
  hack/tools/go.sum
  test/e2e/config/ibmcloud-e2e-powervs.yaml
  test/e2e/config/ibmcloud-e2e-vpc.yaml
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, approved, size/M

#1926 [release-0.7]Update cluster-api to v1.6.8 and golang to 1.21.13
  Dockerfile
  Makefile
  go.mod
  go.sum
  hack/ccm/Dockerfile
  hack/tools/go.mod
  hack/tools/go.sum
  test/e2e/config/ibmcloud-e2e-powervs.yaml
  test/e2e/config/ibmcloud-e2e-vpc.yaml
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, approved, size/M

#1869 Refactor infra creation to improve the overall infra setup time
  cloud/scope/powervs_cluster.go
  controllers/ibmpowervscluster_controller.go
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, size/L, approved

#1895 Vpc extended apis
  api/v1beta1/zz_generated.conversion.go
  api/v1beta2/ibmvpccluster_types.go
  api/v1beta2/types.go
  api/v1beta2/zz_generated.deepcopy.go
  cloud/scope/vpc_cluster.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_ibmpowervsclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_ibmpowervsclustertemplates.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_ibmvpcclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_ibmvpcclustertemplates.yaml
  pkg/cloud/services/resourcemanager/mock/resourcemanager_generated.go
  pkg/cloud/services/resourcemanager/resourcemanager.go
  pkg/cloud/services/resourcemanager/service.go
Labels: lgtm, area/provider/ibmcloud, size/XXL, cncf-cla: yes, ok-to-test, approved

#1894 Update cluster-api to v1.8.1
  .golangci.yml
  Makefile
  api/v1beta1/zz_generated.conversion.go
  api/v1beta1/zz_generated.deepcopy.go
  cloudbuild.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_ibmpowervsclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_ibmpowervsclustertemplates.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_ibmpowervsimages.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_ibmpowervsmachines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_ibmpowervsmachinetemplates.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_ibmvpcclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_ibmvpcclustertemplates.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_ibmvpcmachines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_ibmvpcmachinetemplates.yaml
  go.mod
  go.sum
  hack/ccm/Makefile
  hack/ensure-go.sh
  hack/tools/go.mod
  hack/tools/go.sum
  main.go
  netlify.toml
  test/e2e/config/ibmcloud-e2e-powervs.yaml
  test/e2e/config/ibmcloud-e2e-vpc.yaml
  test/e2e/data/shared/metadata.yaml
  versions.mk
Labels: lgtm, area/provider/ibmcloud, size/XL, cncf-cla: yes, approved

#1931 Return true when PowerVS network is already created during ReconcileNetwork
  cloud/scope/powervs_cluster.go
Labels: lgtm, area/provider/ibmcloud, size/XS, cncf-cla: yes, approved
