Repository kubernetes-sigs/cluster-api-provider-ibmcloud, pull requests merged in 2024-09, with the labels that each got.

#1941 Track and update networking-go-sdk and trivy packages via dependabot
  .github/dependabot.yml
Labels: lgtm, area/provider/ibmcloud, size/XS, cncf-cla: yes, approved

#1946 [release-0.8] Fix CVE-2024-6104
  go.mod
  go.sum
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, size/S, approved

#1947 [release-0.7] Fix CVE-2024-6104
  go.mod
  go.sum
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, size/S, approved

#1949 Fix cluster name references
  cloud/scope/vpc_cluster.go
Labels: lgtm, area/provider/ibmcloud, size/XS, cncf-cla: yes, ok-to-test, approved

#1948 Bump actions version
  .github/workflows/weekly-security-scan.yaml
Labels: lgtm, area/provider/ibmcloud, size/XS, cncf-cla: yes, approved

#1956 Bump golang version to 1.22.7
  Makefile
  hack/ccm/Makefile
  netlify.toml
Labels: lgtm, area/provider/ibmcloud, size/XS, cncf-cla: yes, approved

#1955 Update cluster-api to v1.8.2
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
  test/e2e/config/ibmcloud-e2e-powervs.yaml
  test/e2e/config/ibmcloud-e2e-vpc.yaml
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, approved, size/M

#1901 Attach connections to existing transit gateway when its not there
  api/v1beta2/ibmpowervscluster_types.go
  api/v1beta2/zz_generated.deepcopy.go
  cloud/scope/powervs_cluster.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_ibmpowervsclusters.yaml
  controllers/ibmpowervscluster_controller.go
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, size/L, approved

#1961 Refactor transit gateway status
  cloud/scope/powervs_cluster.go
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, size/L, approved

#1942 VPC: Add Custom Image reconciliation
  api/v1beta2/conditions_consts.go
  api/v1beta2/ibmvpccluster_types.go
  cloud/scope/util.go
  cloud/scope/vpc_cluster.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_ibmvpcclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_ibmvpcclustertemplates.yaml
  controllers/ibmvpccluster_controller.go
  pkg/cloud/services/vpc/mock/vpc_generated.go
  pkg/cloud/services/vpc/service.go
  pkg/cloud/services/vpc/vpc.go
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, ok-to-test, size/L, approved

#1912 Add UT for powervs_cluster file
  cloud/scope/powervs_cluster.go
  cloud/scope/powervs_cluster_test.go
Labels: lgtm, area/provider/ibmcloud, size/XXL, cncf-cla: yes, approved

#1968 [release-0.8] Update cluster-api to v1.7.6
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
  test/e2e/config/ibmcloud-e2e-powervs.yaml
  test/e2e/config/ibmcloud-e2e-vpc.yaml
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, approved, size/M

#1967 Update cluster-api to v1.8.3
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
  test/e2e/config/ibmcloud-e2e-powervs.yaml
  test/e2e/config/ibmcloud-e2e-vpc.yaml
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, approved, size/M

#1964 Redirect stderr to /dev/null to suppress make command warnings.
  hack/version.sh
Labels: lgtm, area/provider/ibmcloud, size/XS, cncf-cla: yes, ok-to-test, approved

#1973 Bump github.com/aquasecurity/trivy to v0.55.1
  controllers/ibmpowervscluster_controller.go
  controllers/ibmpowervsimage_controller.go
  controllers/ibmpowervsmachine_controller.go
  controllers/ibmvpccluster_controller.go
  hack/tools/go.mod
  hack/tools/go.sum
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, approved, size/M

#1974 Add support for JSON output format for logs
  docs/book/src/developer/tilt.md
  go.mod
  main.go
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, approved, size/M

#1976 Ignore unit test coverage files
  .gitignore
Labels: lgtm, area/provider/ibmcloud, size/XS, cncf-cla: yes, approved

#1980 Update IBM Cloud CLI and PowerVS plugin versions
  scripts/ci-e2e.sh
Labels: lgtm, area/provider/ibmcloud, size/XS, cncf-cla: yes, approved

#1982 [release-0.7]Update IBM Cloud CLI and PowerVS plugin versions
  scripts/ci-e2e.sh
Labels: lgtm, area/provider/ibmcloud, size/XS, cncf-cla: yes, approved
