Repository kubernetes-sigs/cluster-api-provider-ibmcloud, pull requests merged in 2024-10, with the labels that each got.

#1984 VPC: Move vpc status update before tagging
  cloud/scope/vpc_cluster.go
Labels: lgtm, needs-ok-to-test, area/provider/ibmcloud, cncf-cla: yes, approved, size/M

#1970 VPC: Add subnet reconciliation
  api/v1beta2/types.go
  cloud/scope/vpc_cluster.go
  controllers/ibmvpccluster_controller.go
  pkg/cloud/services/vpc/mock/vpc_generated.go
  pkg/cloud/services/vpc/service.go
  pkg/cloud/services/vpc/vpc.go
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, ok-to-test, size/L, approved

#1986 Add redirect url for meeting document
  docs/book/book.toml
Labels: lgtm, area/provider/ibmcloud, size/XS, cncf-cla: yes, approved

#1995 [release-0.7]Replace service-target with worskpace after power-iaas plugin update
  scripts/ci-e2e.sh
Labels: lgtm, area/provider/ibmcloud, size/XS, cncf-cla: yes, approved

#1978 VPC: Extend VPC Machine API's
  api/v1beta1/ibmvpc_conversion.go
  api/v1beta1/zz_generated.conversion.go
  api/v1beta2/ibmvpcmachine_types.go
  api/v1beta2/types.go
  api/v1beta2/zz_generated.deepcopy.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_ibmvpcmachines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_ibmvpcmachinetemplates.yaml
Labels: lgtm, area/provider/ibmcloud, size/XL, cncf-cla: yes, ok-to-test, approved

#1998 Update cluster-api to v1.8.4
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
  test/e2e/config/ibmcloud-e2e-powervs.yaml
  test/e2e/config/ibmcloud-e2e-vpc.yaml
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, approved, size/M

#1999 [release-0.8]Update cluster-api to v1.7.7
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
  test/e2e/config/ibmcloud-e2e-powervs.yaml
  test/e2e/config/ibmcloud-e2e-vpc.yaml
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, approved, size/M

#2000 Update golang version to 1.22.8
  Makefile
  hack/ccm/Makefile
  netlify.toml
Labels: lgtm, area/provider/ibmcloud, size/XS, cncf-cla: yes, approved

#1972 ServiceEndpoint overrides saved and used correctly for ignition URL
  cloud/scope/powervs_machine.go
Labels: lgtm, size/XS, cncf-cla: yes, ok-to-test, approved

#1937 Refactor reconcilation of resources
  api/v1beta2/ibmpowervscluster_webhook.go
  cloud/scope/powervs_cluster.go
  cloud/scope/powervs_cluster_test.go
  controllers/ibmpowervscluster_controller.go
Labels: lgtm, area/provider/ibmcloud, size/XXL, cncf-cla: yes, approved

#2006 The typo of Tokyo TG location in region mapping list
  docs/book/src/reference/regions-zones-mapping.md
Labels: lgtm, area/provider/ibmcloud, size/XS, cncf-cla: yes, ok-to-test, approved

#1989 VPC: Extend support for SG's
  cloud/scope/powervs_cluster.go
  cloud/scope/vpc_cluster.go
  controllers/ibmvpccluster_controller.go
  pkg/cloud/services/vpc/mock/vpc_generated.go
  pkg/cloud/services/vpc/service.go
  pkg/cloud/services/vpc/vpc.go
Labels: lgtm, area/provider/ibmcloud, size/XL, cncf-cla: yes, ok-to-test, approved

#2022 Update zoom meeting link, Mailing list link
  README.md
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, size/S, approved

#2004 Configure Loadbalancer back-end pool only for controlplane machines
  cloud/scope/powervs_machine.go
  controllers/ibmpowervsmachine_controller.go
  controllers/ibmpowervsmachine_controller_test.go
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, ok-to-test, size/L, approved

#2003 Add UT for ReconcileVPC and its subfunctions
  cloud/scope/powervs_cluster_test.go
Labels: lgtm, area/provider/ibmcloud, size/XL, cncf-cla: yes, ok-to-test, approved

#1928 Add UT for ReconcileNetwork and its subfunctions
  cloud/scope/powervs_cluster_test.go
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, ok-to-test, size/L, approved

#2017 Add UT for ReconcileVPCSubnet and its subfunctions
  cloud/scope/powervs_cluster_test.go
Labels: lgtm, cncf-cla: yes, ok-to-test, size/L, approved

#2029 Fix PowerVS cluster's load balancer status check
  cloud/scope/powervs_cluster.go
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, size/S, approved
