Repository kubernetes-sigs/cluster-api-provider-ibmcloud, pull requests merged in 2025-04, with the labels that each got.

#2282 fix GO-2025-3553 Vulnerability
  go.mod
  go.sum
  pkg/cloud/services/utils/accounts.go
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, size/S, approved

#2284 [release-0.9] fix GO-2025-3553 Vulnerability
  go.mod
  go.sum
  pkg/cloud/services/utils/accounts.go
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, size/S, approved

#2290 fix release-manifests target
  Makefile
Labels: lgtm, area/provider/ibmcloud, size/XS, cncf-cla: yes, approved

#2289 Remove deprecated admission interfaces
  api/v1beta2/ibmpowervscluster_webhook.go
  api/v1beta2/ibmpowervsclustertemplate_webhook.go
  api/v1beta2/ibmpowervsclustertemplate_webhook_test.go
  api/v1beta2/ibmpowervsimage_webhook.go
  api/v1beta2/ibmpowervsmachine_webhook.go
  api/v1beta2/ibmpowervsmachine_webhook_test.go
  api/v1beta2/ibmpowervsmachinetemplate_webhook.go
  api/v1beta2/ibmpowervsmachinetemplate_webhook_test.go
  api/v1beta2/ibmvpccluster_webhook.go
  api/v1beta2/ibmvpcmachine_webhook.go
  api/v1beta2/ibmvpcmachine_webhook_test.go
  api/v1beta2/ibmvpcmachinetemplate_webhook.go
  api/v1beta2/ibmvpcmachinetemplate_webhook_test.go
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, size/L, approved

#2292 generate templates pointing to registry.k8s.io
  templates/addons/crs-powervs.yaml
  templates/addons/crs.yaml
  templates/cluster-template-powervs-clusterclass.yaml
  templates/cluster-template-powervs-create-infra.yaml
  templates/cluster-template-powervs.yaml
  templates/cluster-template-vpc-clusterclass.yaml
  templates/cluster-template.yaml
  test/e2e/data/templates/cluster-template-powervs-md-remediation.yaml
  test/e2e/data/templates/cluster-template-vpc.yaml
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, size/S, approved

#2287 Move away from use of controller-runtime scheme while registering api types
  api/v1beta2/groupversion_info.go
  api/v1beta2/ibmpowervscluster_types.go
  api/v1beta2/ibmpowervsclustertemplate_types.go
  api/v1beta2/ibmpowervsimage_types.go
  api/v1beta2/ibmpowervsmachine_types.go
  api/v1beta2/ibmpowervsmachinetemplate_types.go
  api/v1beta2/ibmvpccluster_types.go
  api/v1beta2/ibmvpcclustertemplate_types.go
  api/v1beta2/ibmvpcmachine_types.go
  api/v1beta2/ibmvpcmachinetemplate_types.go
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, approved, size/M

#2293 Bump github.com/golangci/golangci-lint from 1.59.1 to 1.64.8 in /hack/tools
  .golangci.yml
  hack/tools/go.mod
  hack/tools/go.sum
Labels: lgtm, area/provider/ibmcloud, size/XL, cncf-cla: yes, approved

#2296 Move wehbooks out of api directory to seperate directory
  Dockerfile
  cloud/scope/powervs_machine.go
  cloud/scope/suite_test.go
  controllers/suite_test.go
  internal/webhooks/common.go
  internal/webhooks/common_test.go
  internal/webhooks/doc.go
  internal/webhooks/ibmpowervscluster.go
  internal/webhooks/ibmpowervscluster_test.go
  internal/webhooks/ibmpowervsclustertemplate.go
  internal/webhooks/ibmpowervsclustertemplate_test.go
  internal/webhooks/ibmpowervsimage.go
  internal/webhooks/ibmpowervsmachine.go
  internal/webhooks/ibmpowervsmachine_test.go
  internal/webhooks/ibmpowervsmachinetemplate.go
  internal/webhooks/ibmpowervsmachinetemplate_test.go
  internal/webhooks/ibmvpccluster.go
  internal/webhooks/ibmvpcmachine.go
  internal/webhooks/ibmvpcmachine_test.go
  internal/webhooks/ibmvpcmachinetemplate.go
  internal/webhooks/ibmvpcmachinetemplate_test.go
  internal/webhooks/suite_test.go
  internal/webhooks/util.go
  main.go
Labels: lgtm, area/provider/ibmcloud, size/XXL, cncf-cla: yes, approved

#2297 Fixed bootVolume name bug
  cloud/scope/machine.go
Labels: lgtm, area/provider/ibmcloud, size/XS, cncf-cla: yes, ok-to-test, approved

#2272 Adopt CAPI v2beta2 status changes and respective controller changes for IBMPowerVSMachine
  api/v1beta1/ibmpowervs_conversion.go
  api/v1beta1/zz_generated.conversion.go
  api/v1beta2/conditions_consts.go
  api/v1beta2/ibmpowervsmachine_types.go
  api/v1beta2/zz_generated.deepcopy.go
  cloud/scope/powervs_machine.go
  cloud/scope/powervs_machine_test.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_ibmpowervsmachines.yaml
  controllers/ibmpowervsmachine_controller.go
  controllers/ibmpowervsmachine_controller_test.go
  main.go
Labels: lgtm, area/provider/ibmcloud, size/XXL, cncf-cla: yes, approved

#2303 Bump go.uber.org/mock from 0.4.0 to 0.5.1 in /hack/tools
  hack/tools/go.mod
  hack/tools/go.sum
  pkg/cloud/services/cos/mock/cos_generated.go
  pkg/cloud/services/globaltagging/mock/globaltagging_generated.go
  pkg/cloud/services/powervs/mock/powervs_generated.go
  pkg/cloud/services/resourcecontroller/mock/resourcecontroller_generated.go
  pkg/cloud/services/resourcemanager/mock/resourcemanager_generated.go
  pkg/cloud/services/transitgateway/mock/transitgateway_generated.go
  pkg/cloud/services/vpc/mock/vpc_generated.go
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, size/S, approved

#2295 Update cluster-api to v1.10.0-beta.1
  Makefile
  config/crd/bases/infrastructure.cluster.x-k8s.io_ibmpowervsclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_ibmpowervsclustertemplates.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_ibmpowervsimages.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_ibmpowervsmachines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_ibmpowervsmachinetemplates.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_ibmvpcclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_ibmvpcclustertemplates.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_ibmvpcmachines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_ibmvpcmachinetemplates.yaml
  go.mod
  go.sum
  hack/ccm/Makefile
  hack/tools/go.mod
  hack/tools/go.sum
  netlify.toml
  scripts/ci-test.sh
  scripts/fetch_ext_bins.sh
  test/e2e/config/ibmcloud-e2e-powervs.yaml
  test/e2e/config/ibmcloud-e2e-vpc.yaml
  test/e2e/data/shared/metadata.yaml
  test/e2e/e2e_test.go
  test/e2e/suite_test.go
Labels: lgtm, area/provider/ibmcloud, size/XL, cncf-cla: yes, approved

#2305 Add release-notes generation tooling
  Makefile
  docs/book/src/developer/release.md
  hack/tools/Makefile
  hack/tools/go.mod
  hack/tools/go.sum
  hack/tools/tools.go
  scripts/go_install.sh
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, size/L, approved

#2304 Add the e1050 System Type
  api/v1beta2/ibmpowervsmachine_types.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_ibmpowervsmachines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_ibmpowervsmachinetemplates.yaml
  go.mod
  go.sum
Labels: lgtm, cncf-cla: yes, ok-to-test, approved, size/M

#2308 Add kubeconfig and cluster config path while deleting the cluster in e2e
  test/e2e/e2e_test.go
Labels: lgtm, area/provider/ibmcloud, size/XS, cncf-cla: yes, approved

#2314 Update cloud-proivder-powervs commit to build new ccm image
  hack/ccm/Makefile
Labels: lgtm, area/provider/ibmcloud, size/XS, cncf-cla: yes, approved

#2320 Update cloud-controller-manager container image to latest image
  templates/addons/crs-powervs.yaml
  templates/addons/crs.yaml
  templates/cluster-template-powervs-clusterclass.yaml
  templates/cluster-template-powervs-create-infra.yaml
  templates/cluster-template-powervs.yaml
  templates/cluster-template-vpc-clusterclass.yaml
  templates/cluster-template.yaml
  test/e2e/data/templates/cluster-template-powervs-md-remediation.yaml
  test/e2e/data/templates/cluster-template-vpc.yaml
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, size/S, approved

#2275 Added support for additionalVolumes in VPCMachines
  api/v1beta1/zz_generated.conversion.go
  api/v1beta2/ibmvpcmachine_types.go
  api/v1beta2/zz_generated.deepcopy.go
  cloud/scope/machine.go
  cloud/scope/machine_test.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_ibmvpcmachines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_ibmvpcmachinetemplates.yaml
  controllers/ibmvpcmachine_controller.go
  controllers/ibmvpcmachine_controller_test.go
  internal/webhooks/common.go
  internal/webhooks/common_test.go
  internal/webhooks/ibmvpcmachine.go
  pkg/cloud/services/vpc/mock/vpc_generated.go
  pkg/cloud/services/vpc/service.go
  pkg/cloud/services/vpc/vpc.go
  templates/cluster-template.yaml
  templates/cluster-template/md.yaml
  test/e2e/data/templates/cluster-template-vpc.yaml
Labels: lgtm, area/provider/ibmcloud, size/XL, cncf-cla: yes, ok-to-test, approved

#2323 Change the number of ginkgo nodes to 1 to run the e2e tests serially
  Makefile
Labels: lgtm, area/provider/ibmcloud, size/XS, cncf-cla: yes, approved

#2325 Update cluster-api to v1.10.0
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
  test/e2e/config/ibmcloud-e2e-powervs.yaml
  test/e2e/config/ibmcloud-e2e-vpc.yaml
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, approved, size/M

#2327 [release-0.9] Update cluster-api to v1.8.12
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
  test/e2e/config/ibmcloud-e2e-powervs.yaml
  test/e2e/config/ibmcloud-e2e-vpc.yaml
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, approved, size/M

#2326 [release-0.10] Update cluster-api to v1.9.7
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
  test/e2e/config/ibmcloud-e2e-powervs.yaml
  test/e2e/config/ibmcloud-e2e-vpc.yaml
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, approved, size/M

#2310 Fix trivy scan flow
  Makefile
  hack/ensure-trivy.sh
  hack/tools/Makefile
  hack/tools/go.mod
  hack/tools/go.sum
  hack/tools/tools.go
  hack/verify-container-images.sh
Labels: lgtm, area/provider/ibmcloud, size/XXL, cncf-cla: yes, approved

#2312 Adopt CAPI v2beta2 status changes and respective controller changes for IBMPowerVSCluster
  api/v1beta1/zz_generated.conversion.go
  api/v1beta2/conditions_consts.go
  api/v1beta2/ibmpowervscluster_types.go
  api/v1beta2/zz_generated.deepcopy.go
  cloud/scope/powervs_cluster.go
  cloud/scope/powervs_cluster_test.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_ibmpowervsclusters.yaml
  controllers/ibmpowervscluster_controller.go
  controllers/ibmpowervscluster_controller_test.go
  controllers/ibmpowervsmachine_controller.go
  go.mod
Labels: lgtm, area/provider/ibmcloud, size/XXL, cncf-cla: yes, approved

#2329 Fixed additionalvolume fields in e2e template
  templates/cluster-template.yaml
  templates/cluster-template/md.yaml
  test/e2e/data/templates/cluster-template-vpc.yaml
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, size/S, ok-to-test, approved

#2334 Update cluster-api to v1.10.1
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
  test/e2e/config/ibmcloud-e2e-powervs.yaml
  test/e2e/config/ibmcloud-e2e-vpc.yaml
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, approved, size/M

#2149 Added flag to disable http/2
  main.go
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, size/S, ok-to-test, approved

#2335 Update cloud-proivder-powervs commit
  hack/ccm/Makefile
  hack/verify-container-images.sh
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, size/S, approved
