Repository kubernetes-sigs/cluster-api-provider-ibmcloud, pull requests merged in 2025-01, with the labels that each got.

#2118 bump gcr.io/k8s-staging-test-infra/gcb-docker-gcloud to v20241229-5dc092c636
  cloudbuild.yaml
Labels: lgtm, area/provider/ibmcloud, size/XS, cncf-cla: yes, approved

#2120 pin go version to 1.22.9 in tools
  hack/tools/go.mod
Labels: lgtm, area/provider/ibmcloud, size/XS, cncf-cla: yes, approved

#2125 Bump golang version to 1.22.10
  Makefile
  hack/ccm/Makefile
  netlify.toml
Labels: lgtm, area/provider/ibmcloud, size/XS, cncf-cla: yes, approved

#2126 Pin workflow to run on ubuntu-24.04
  .github/workflows/weekly-security-scan.yaml
Labels: lgtm, area/provider/ibmcloud, size/XS, cncf-cla: yes, approved

#2124 Add templates for cluster-api version update and release tracker
  .github/ISSUE_TEMPLATE/cluster_api_version_update.md
  .github/ISSUE_TEMPLATE/release.md
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, approved, size/M

#2073 Fix warnings in kustomization file
  config/crd/kustomization.yaml
  config/default/kustomization.yaml
  test/e2e/data/templates/cluster-template-powervs-md-remediation/kustomization.yaml
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, ok-to-test, size/L, approved

#2072 Yamllint enhancement
  .github/workflows/validate-yaml-lint.yaml
  .yamllint
  Makefile
  templates/bases/powervs/kcp.yaml
  templates/bases/vpc/kcp.yaml
  templates/cluster-template-powervs-clusterclass/cluster-with-kcp.yaml
  templates/cluster-template-powervs/kcp.yaml
  templates/cluster-template-vpc-clusterclass/cluster-with-kcp.yaml
  templates/cluster-template/cluster.yaml
  templates/cluster-template/kcp.yaml
  test/e2e/data/cni/calico/calico.yaml
Labels: lgtm, cncf-cla: yes, ok-to-test, size/L, approved

#2141 BUG: IBM Cloud Infra: Return existing VPC ID
  cloud/scope/vpc_cluster.go
Labels: lgtm, area/provider/ibmcloud, size/XS, cncf-cla: yes, ok-to-test, approved

#2146 Bump cluster-api to v1.9.4
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
  test/e2e/config/ibmcloud-e2e-powervs.yaml
  test/e2e/config/ibmcloud-e2e-vpc.yaml
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, approved, size/M

#2147 [release-0.9]Bump cluster-api to v1.8.9
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
  test/e2e/config/ibmcloud-e2e-powervs.yaml
  test/e2e/config/ibmcloud-e2e-vpc.yaml
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, approved, size/M

#2122 remove deprecated v1 provider id format
  Makefile
  cloud/scope/machine.go
  cloud/scope/machine_test.go
  cloud/scope/powervs_machine.go
  cloud/scope/powervs_machine_test.go
  controllers/ibmpowervsmachine_controller_test.go
  controllers/ibmvpcmachine_controller_test.go
  main.go
  pkg/cloud/services/utils/accounts.go
  pkg/options/options.go
  templates/cluster-template-powervs.yaml
  templates/cluster-template-powervs/kcp.yaml
  templates/cluster-template-powervs/kubeadm-config.yaml
  templates/cluster-template-powervs/kustomization.yaml
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, size/L, approved

#2151 Infrastructure: Fix machine placement target defaults
  api/v1beta2/types.go
Labels: lgtm, area/provider/ibmcloud, size/XS, cncf-cla: yes, ok-to-test, approved
