Repository kubernetes-sigs/cluster-api-provider-ibmcloud, pull requests merged in 2025-02, with the labels that each got.

#2160 bump golang to v1.22.11
  Makefile
  hack/ccm/Makefile
  netlify.toml
Labels: lgtm, area/provider/ibmcloud, size/XS, cncf-cla: yes, approved

#2161 [release-0.9] Bump golang to v1.22.11
  Makefile
  hack/ccm/Makefile
  netlify.toml
Labels: lgtm, area/provider/ibmcloud, size/XS, cncf-cla: yes, approved

#2139 Proposal for adding Additional Disks to node
  docs/proposal/additional-disks.md
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, ok-to-test, approved, size/M

#2165 [release-0.9] Fix powervs machine image link
  docs/book/src/machine-images/powervs.md
Labels: lgtm, area/provider/ibmcloud, size/XS, cncf-cla: yes, approved

#2169 fix linters related warnings
  .golangci.yml
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, size/S, approved

#2168 make powervs cluster setup with external cloud provider as default
  Makefile
  docs/book/src/developer/tilt.md
  docs/book/src/topics/powervs/creating-a-cluster.md
  docs/book/src/topics/vpc/creating-a-cluster.md
  templates/README.md
  templates/cluster-template-powervs.yaml
  templates/cluster-template-powervs/cluster.yaml
  templates/cluster-template-powervs/kcp.yaml
  templates/cluster-template-powervs/kubeadm-config.yaml
  templates/cluster-template-powervs/kustomization.yaml
  test/e2e/data/templates/cluster-template-powervs-md-remediation/kustomization.yaml
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, size/L, approved

#2174 Update the commit-hash for PowerVS Cloud Controller
  hack/ccm/Makefile
Labels: lgtm, area/provider/ibmcloud, size/XS, cncf-cla: yes, approved

#2144 Add uts for setProviderID
  cloud/scope/machine_test.go
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, size/S, ok-to-test, approved

#2181 Bump golang to v1.22.12
  Makefile
  hack/ccm/Makefile
  netlify.toml
Labels: lgtm, area/provider/ibmcloud, size/XS, cncf-cla: yes, approved

#2162 Enhance local development documentation
  docs/book/src/developer/e2e.md
  docs/book/src/developer/tilt.md
  docs/book/src/topics/powervs/creating-a-cluster.md
  docs/book/src/topics/vpc/creating-a-cluster.md
  docs/book/src/user/troubleshooting.md
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, size/S, ok-to-test, approved

#2184 Enhance Feature Request Template to Improve Clarity and Context
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, size/S, ok-to-test, approved

#2188 fix powervs_cloud_controller image build
  hack/ccm/Makefile
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, approved, size/M

#2191 update powervs-cloud-controller image tag
  templates/addons/crs-powervs.yaml
  templates/addons/crs.yaml
  templates/cluster-template-powervs-clusterclass.yaml
  templates/cluster-template-powervs-create-infra.yaml
  templates/cluster-template-powervs.yaml
  templates/cluster-template-vpc-clusterclass.yaml
  templates/cluster-template.yaml
  test/e2e/data/templates/cluster-template-powervs-md-remediation.yaml
  test/e2e/data/templates/cluster-template-vpc.yaml
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, size/S, approved

#2196 Fix release issue template description
  .github/ISSUE_TEMPLATE/release.md
Labels: lgtm, area/provider/ibmcloud, size/XS, cncf-cla: yes, approved

#2200 Post v0.10.0 release housekeeping
  .github/workflows/weekly-security-scan.yaml
  README.md
  docs/book/src/developer/release-support-guidelines.md
  metadata.yaml
  test/e2e/config/ibmcloud-e2e-powervs.yaml
  test/e2e/config/ibmcloud-e2e-vpc.yaml
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, size/S, approved

#2204 Bump cluster-api to v1.9.5
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
  test/e2e/config/ibmcloud-e2e-powervs.yaml
  test/e2e/config/ibmcloud-e2e-vpc.yaml
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, approved, size/M

#2205 [release-0.9] Bump cluster-api to v1.8.10
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
  test/e2e/config/ibmcloud-e2e-powervs.yaml
  test/e2e/config/ibmcloud-e2e-vpc.yaml
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, approved, size/M

#2207 [release-0.10] Update docs with v0.10.0 references
  README.md
  docs/book/src/developer/release-support-guidelines.md
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, size/S, approved

#2209 Add release-0-10 book link
  docs/book/src/introduction.md
Labels: lgtm, area/provider/ibmcloud, size/XS, cncf-cla: yes, approved

#2213 Build and publish vpc image for k8s version 1.31.4
  docs/book/src/machine-images/vpc.md
  scripts/ci-e2e.sh
  test/e2e/config/ibmcloud-e2e-vpc.yaml
Labels: lgtm, area/provider/ibmcloud, size/XS, cncf-cla: yes, ok-to-test, approved

#2215 Update CCM image to fix the PowerVS CI
  hack/ccm/Makefile
  templates/addons/crs-powervs.yaml
  templates/addons/crs.yaml
  templates/cluster-template-powervs-clusterclass.yaml
  templates/cluster-template-powervs-create-infra.yaml
  templates/cluster-template-powervs.yaml
  templates/cluster-template-vpc-clusterclass.yaml
  templates/cluster-template.yaml
  test/e2e/data/templates/cluster-template-powervs-md-remediation.yaml
  test/e2e/data/templates/cluster-template-vpc.yaml
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, size/S, approved

#2218 Update the release issue template
  .github/ISSUE_TEMPLATE/release.md
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, size/S, approved
