Repository kubernetes-sigs/cluster-api-provider-ibmcloud, pull requests merged in 2025-08, with the labels that each got.

#2429 Adopt v1beta2 conditions for IBM VPC cluster
  api/v1beta1/zz_generated.conversion.go
  api/v1beta2/conditions_consts.go
  api/v1beta2/ibmvpccluster_types.go
  api/v1beta2/zz_generated.deepcopy.go
  cloud/scope/cluster.go
  cloud/scope/cluster_test.go
  cloud/scope/vpc_cluster.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_ibmvpcclusters.yaml
  controllers/ibmpowervsmachine_controller.go
  controllers/ibmvpccluster_controller.go
  controllers/ibmvpccluster_controller_test.go
Labels: lgtm, area/provider/ibmcloud, size/XL, cncf-cla: yes, approved

#2455 Bump VPC CI image to v1.33.0
  docs/book/src/machine-images/vpc.md
  scripts/ci-e2e.sh
  test/e2e/config/ibmcloud-e2e-vpc.yaml
Labels: lgtm, area/provider/ibmcloud, size/XS, cncf-cla: yes, approved

#2457 Loosen the linter's rule to allow bumping of golangci-lint
  .golangci.yml
  hack/tools/go.mod
  hack/tools/go.sum
  test/helpers/envtest.go
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, size/L, approved

#2460 Fix trivy security scan vulnerabilities
  Makefile
  hack/ccm/Makefile
  hack/ccm/cloudbuild.yaml
Labels: lgtm, area/provider/ibmcloud, size/XS, cncf-cla: yes, approved

#2465 [release-0.11] Fix trivy security scan vulnerabilities
  .golangci.yml
  Makefile
  cloudbuild.yaml
  hack/ccm/Makefile
  hack/ccm/cloudbuild.yaml
  netlify.toml
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, size/S, approved

#2466 Update cluster-api version to v1.11.0
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
  test/e2e/config/ibmcloud-e2e-powervs.yaml
  test/e2e/config/ibmcloud-e2e-vpc.yaml
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, approved, size/M

#2412 Add v1beta2 changes to IBMPowerVSImage
  api/v1beta1/ibmpowervs_conversion.go
  api/v1beta1/zz_generated.conversion.go
  api/v1beta2/conditions_consts.go
  api/v1beta2/ibmpowervsimage_types.go
  api/v1beta2/types.go
  api/v1beta2/zz_generated.deepcopy.go
  cloud/scope/powervs_image.go
  cloud/scope/powervs_image_test.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_ibmpowervsimages.yaml
  controllers/ibmpowervsimage_controller.go
  controllers/ibmpowervsimage_controller_test.go
Labels: lgtm, area/provider/ibmcloud, size/XL, cncf-cla: yes, ok-to-test, approved

#2468 Update cluster class templates with v1beta2 API changes
  templates/cluster-template-powervs-clusterclass.yaml
  templates/cluster-template-powervs-clusterclass/cluster-with-kcp.yaml
  templates/cluster-template-vpc-clusterclass.yaml
  templates/cluster-template-vpc-clusterclass/cluster-with-kcp.yaml
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, size/L, approved

#2403 Added linkcheck to makefile
  .github/ISSUE_TEMPLATE/cluster_api_version_update.md
  .github/workflows/validate-yaml-lint.yaml
  Makefile
  docs/book/src/developer/conversion.md
  docs/book/src/developer/dependencies.md
  docs/book/src/developer/index.md
  docs/book/src/developer/tilt.md
  docs/book/src/getting-started.md
  docs/book/src/introduction.md
  docs/book/src/machine-images/index.md
  docs/book/src/reference/reference.md
  docs/book/src/topics/capibmadm/powervs/index.md
  docs/book/src/topics/capibmadm/vpc/index.md
  docs/book/src/topics/index.md
  docs/book/src/topics/powervs/creating-a-cluster.md
  docs/book/src/topics/powervs/index.md
  docs/book/src/topics/powervs/prerequisites.md
  docs/book/src/topics/vpc/creating-a-cluster.md
  docs/book/src/topics/vpc/index.md
  docs/book/src/topics/vpc/prerequisites.md
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, ok-to-test, size/L, approved

#2471 Minor updates to ci-e2e.sh
  hack/boskos.sh
  scripts/ci-e2e.sh
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, size/S, approved

#2470 Update capibmadm cli tool installation guide
  .github/ISSUE_TEMPLATE/release.md
  docs/book/src/topics/capibmadm/index.md
  docs/book/theme/css/custom.css
  hack/tools/tools.go
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, ok-to-test, approved, size/M
