Repository kubernetes-sigs/cluster-api-provider-ibmcloud, pull requests merged in 2025-05, with the labels that each got.

#2269 Fix priority between network and DHCP server
  api/v1beta2/ibmpowervscluster_types.go
  cloud/scope/powervs_cluster.go
  cloud/scope/powervs_cluster_test.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_ibmpowervsclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_ibmpowervsclustertemplates.yaml
  internal/webhooks/ibmpowervscluster.go
  internal/webhooks/ibmpowervscluster_test.go
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, size/L, approved

#2336 Update cloud-controller-manager container image to latest image
  templates/addons/crs-powervs.yaml
  templates/addons/crs.yaml
  templates/cluster-template-powervs-clusterclass.yaml
  templates/cluster-template-powervs-create-infra.yaml
  templates/cluster-template-powervs.yaml
  templates/cluster-template-vpc-clusterclass.yaml
  templates/cluster-template.yaml
  test/e2e/data/templates/cluster-template-powervs-md-remediation.yaml
  test/e2e/data/templates/cluster-template-vpc.yaml
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, size/S, approved

#2338 drop older k8s images
  docs/book/src/machine-images/powervs.md
  docs/book/src/machine-images/vpc.md
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, approved, size/M

#2340 Update documentation to contain post-release tasks
  docs/book/src/developer/release.md
Labels: lgtm, kind/documentation, area/provider/ibmcloud, size/XS, cncf-cla: yes, approved

#2342 revert additionalVolumes from templates
  templates/cluster-template.yaml
  templates/cluster-template/md.yaml
  test/e2e/data/templates/cluster-template-vpc.yaml
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, size/S, approved

#2339 Enhance UT for ReconcileCOSInstance method
  cloud/scope/powervs_cluster.go
  cloud/scope/powervs_cluster_test.go
  cloud/scope/powervs_machine.go
  pkg/cloud/services/cos/service.go
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, size/L, approved

#2347 Update trouble shooting guide with instructions to debug CCM issues
  docs/book/src/user/troubleshooting.md
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, size/L, approved

#2349 [release-0.10] update k8s machine images
  docs/book/src/machine-images/powervs.md
  docs/book/src/machine-images/vpc.md
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, approved, size/M

#2350 [release-0.9] update k8s machine images
  docs/book/src/machine-images/powervs.md
  docs/book/src/machine-images/vpc.md
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, approved, size/M

#2352 Revert "Added support for additionalVolumes in VPCMachines (#2275)"
  api/v1beta1/zz_generated.conversion.go
  api/v1beta2/ibmvpcmachine_types.go
  api/v1beta2/zz_generated.deepcopy.go
  cloud/scope/machine.go
  cloud/scope/machine_test.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_ibmvpcmachines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_ibmvpcmachinetemplates.yaml
  controllers/ibmvpcmachine_controller.go
  controllers/ibmvpcmachine_controller_test.go
  internal/webhooks/common.go
  internal/webhooks/common_test.go
  internal/webhooks/ibmvpcmachine.go
  pkg/cloud/services/vpc/mock/vpc_generated.go
  pkg/cloud/services/vpc/service.go
  pkg/cloud/services/vpc/vpc.go
Labels: lgtm, area/provider/ibmcloud, size/XL, cncf-cla: yes, approved

#2351 update k8s machine images
  docs/book/src/machine-images/powervs.md
  docs/book/src/machine-images/vpc.md
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, size/S, approved

#2357 Post v0.11.0 release housekeeping
  .github/workflows/weekly-security-scan.yaml
  README.md
  docs/book/src/developer/release-support-guidelines.md
  metadata.yaml
  test/e2e/config/ibmcloud-e2e-powervs.yaml
  test/e2e/config/ibmcloud-e2e-vpc.yaml
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, size/S, approved

#2358 [release-0.10] bump go to 1.23.8 and add CVEs to trivyignore
  .trivyignore
  Makefile
  netlify.toml
Labels: lgtm, area/provider/ibmcloud, size/XS, cncf-cla: yes, approved

#2223 Update documentation for release process
  RELEASE.md
  docs/book/src/developer/release.md
Labels: lgtm, kind/documentation, area/provider/ibmcloud, cncf-cla: yes, approved, size/M

#2371 [release-0.10]Update cluster-api to v1.9.8
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
  test/e2e/config/ibmcloud-e2e-powervs.yaml
  test/e2e/config/ibmcloud-e2e-vpc.yaml
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, approved, size/M

#2372 Bump PowerVS CI image to v 1.32.3
  docs/book/src/machine-images/powervs.md
  scripts/ci-e2e.sh
  test/e2e/config/ibmcloud-e2e-powervs.yaml
Labels: lgtm, area/provider/ibmcloud, size/XS, cncf-cla: yes, approved
