Repository kubernetes-sigs/cluster-api-provider-ibmcloud, pull requests merged in 2025-03, with the labels that each got.

#2234 Bump honnef.co/go/tools
  api/v1beta2/suite_test.go
  cloud/scope/suite_test.go
  controllers/suite_test.go
  hack/tools/go.mod
  hack/tools/go.sum
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, approved, size/M

#2232 Infra: Fix Machine GT endpoint management
  cloud/scope/machine.go
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, size/S, ok-to-test, approved

#2240 streamline the CCM image build process
  hack/ccm/Dockerfile
  hack/ccm/Makefile
  hack/ccm/cloudbuild.yaml
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, approved, size/M

#2245 fix platform flags in ccm build
  hack/ccm/Dockerfile
Labels: lgtm, area/provider/ibmcloud, size/XS, cncf-cla: yes, approved

#2247 [release-0.9] Bump honnef.co/go/tools
  api/v1beta2/suite_test.go
  cloud/scope/suite_test.go
  controllers/suite_test.go
  hack/tools/go.mod
  hack/tools/go.sum
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, approved, size/M

#2244 Build and publish vpc image for k8s version 1.30.4
  docs/book/src/machine-images/vpc.md
  scripts/ci-e2e.sh
  test/e2e/config/ibmcloud-e2e-vpc.yaml
Labels: lgtm, area/provider/ibmcloud, size/XS, cncf-cla: yes, ok-to-test, approved

#2254 Update meeting time and zoom link
  docs/book/src/introduction.md
Labels: lgtm, area/provider/ibmcloud, size/XS, cncf-cla: yes, approved

#2173 Add proposal for assigning additional listener to specific machines
  docs/images/additional-listener-code-workflow.png
  docs/images/additional-listener-design-diagram.png
  docs/images/additional-listener-examples.excalidraw
  docs/images/additional-listener-examples.png
  docs/images/additional_listener_code_workflow.excalidraw
  docs/images/additional_listener_design_diagram.excalidraw
  docs/proposal/20250207-additional-listener.md
Labels: lgtm, area/provider/ibmcloud, size/XXL, cncf-cla: yes, ok-to-test, tide/merge-method-squash, approved

#2262 Bump gcb-docker-gcloud to v20241229-5dc092c636
  cloudbuild.yaml
Labels: lgtm, area/provider/ibmcloud, size/XS, cncf-cla: yes, approved

#2265 [release-0.9] Bump cluster-api to v1.8.11
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
  test/e2e/config/ibmcloud-e2e-powervs.yaml
  test/e2e/config/ibmcloud-e2e-vpc.yaml
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, approved, size/M

#2266 [release-0.10] Bump cluster-api to v1.9.6
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
  test/e2e/config/ibmcloud-e2e-powervs.yaml
  test/e2e/config/ibmcloud-e2e-vpc.yaml
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, approved, size/M

#2267 [release-0.10] Ignore CVE-2025-22870
  .trivyignore
Labels: lgtm, area/provider/ibmcloud, size/XS, cncf-cla: yes, approved

#2172 Add reference links for environment variables for VPC and PowerVS
  docs/book/src/topics/powervs/creating-a-cluster.md
  docs/book/src/topics/vpc/creating-a-cluster.md
Labels: lgtm, area/provider/ibmcloud, cncf-cla: yes, size/S, ok-to-test, approved
